### ISSUE TITLE
[Beta 2.0.0] Feature Request - Match on fields other than Slug, Title, ID

### ISSUE THREAD

**Issue by joshua-martin** [verbb/feed-me#139]
Would it be possible to match related elements on more than Slug, Title or ID?

I've added the below code to get this functionality, but wondered if this is something you would consider building in as default.

**/feedme/FeedMe/FieldTypes/EntriesFeedMeFieldType.php**
_Line 62_

```
// Check if we've specified which attribute we're trying to match against
$attribute = Hash::get($fieldData, 'options.match', 'title');

if ($attribute == 'custom') {
    $attribute = Hash::get($fieldData, 'options.custom', 'title');
}
```

**/feedme/templates/_includes/fields/entries.html**
_Line 33_
```
{{ forms.selectField({
    name: fieldHandle ~ '-options-match',
    options: [
        { value: 'title', label: 'Title' | t },
        { value: 'id', label: 'ID' | t },
        { value: 'slug', label: 'Slug' | t },
        { value: 'custom', label: 'a custom field' | t }
     ],
     value: feed.fieldMapping[fieldHandle ~ '-options-match'] ?? '',
}) }}

{% for tab in craft.fields.getLayoutById(entryType.fieldLayoutId).getTabs() %}
    {% for fieldtype in tab.getFields() %}
        {% set field = fieldtype.getField() %}
        {% set fields = fields | merge([{ value: field.handle, label: field.name }]) %}
    {% endfor %}
{% endfor %}

<div class="element-match">
    <span>{{ 'Match custom field:' | t }}</span>
    {{ forms.selectField({
        name: fieldHandle ~ '-options-custom',
        options: fields,
        value: feed.fieldMapping[fieldHandle ~ '-options-custom'] ?? ''
    }) }}
</div>
```

**Comment by engram-design** [comment]
Its certainly an option we want to include, but just thinking it through. In your example, the custom fields being displayed in the dropdown would be from the same section/entrytype that you're importing to. This isn't always the case, and most of the time you'd want to match against entries from another section, which have their own custom fields.

So essentially, that dropdown would either need to be contextual to the section/entrytype the field maps to, or load in every single custom field possible across the board.

**Comment by joshua-martin** [comment]
Yes thats a good point. Our edge case for this update means that we only search within a specific section, so we only needed to match on the custom fields within that section.

It would be too much to display every custom field, but arguably this might be the best option as someone may want to relate to data within 3 or 4 different channels as we currently do.

**Comment by engram-design** [comment]
This has been improved in Feed Me 3.x.
