### ISSUE TITLE
Backup removal/rotation

### ISSUE THREAD

**Issue by ChrisRally** [verbb/feed-me#14]
It would be great if the plugin could also remove/rotate older backups, as we've found very quickly running a couple of feeds you can run into GBs of database backups!

**Comment by engram-design** [comment]
Excellent idea, I also want to build in back restoration as well, so will add this to the list. Thanks!

**Comment by engram-design** [comment]
We've added this in [2.0.10](https://verbb.io/craft-plugins/feed-me/download?v=2). Its controlled by a config setting `backupLimit`, but is by default set to 100. See https://verbb.io/craft-plugins/feed-me/docs/get-started/configuration
