### ISSUE TITLE
Craft 3 support

### ISSUE THREAD

**Issue by engram-design** [verbb/feed-me#141]

**Comment by engram-design** [comment]
Including Composer support

**Comment by ryanmasuga** [comment]
Looking around for import options for Craft 3 and there isn't much out there at this point. We've used Feed Me on Craft 2, and are eager to try out the Craft 3 version. This thread is over a year old...any progress on this front? We'd be happy to beta test.

**Comment by engram-design** [comment]
@ryanmasuga There's a fair bit of demand for Feed Me for Craft 3, but we're working hard on getting it ready. We're expecting a beta available by end of March.

**Comment by engram-design** [comment]
This has been implemented in [3.0.0-beta.1 for Craft 3](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.1)
