### ISSUE TITLE
[Beta 2.0.0] Ability to specify field for uploaded Asset's title and/or file name

### ISSUE THREAD

**Issue by howells** [verbb/feed-me#157]
In a current project I'm pulling in images from very verbose, garbage URLs so that filenames and titles of the newly created Assets are as verbose and garbage. It'd be great if we could specify which field from which new assets' titles/filenames could be generated.

**Comment by eablokker** [comment]
Also to be able to specify other custom fields on assets, like the image alt text.

**Comment by engram-design** [comment]
Added in [3.1.1](https://github.com/verbb/feed-me/releases/tag/3.1.1) through the inclusion of a second field for the Filename and URL or Path.
