### ISSUE TITLE
FR: Duplicate feed button

### ISSUE THREAD

**Issue by ldstevens** [verbb/feed-me#161]
I've often found myself duplicating feeds while working on a big import, so that I can test different source files without having to go through the field mapping every time. Currently I just dupe the row in the DB directly and edit the source URL, but it might be handy to have it in the UI.

**Comment by engram-design** [comment]
For sure - just have to make some space in the Index Table! For the moment, duplicating via the `feedme_feeds` table is your best bet.

**Comment by engram-design** [comment]
Added in [2.0.7](https://github.com/verbb/feed-me/releases/tag/2.0.7)
