### ISSUE TITLE
FR: Import progress URL shouldn't trigger new import

### ISSUE THREAD

**Issue by ldstevens** [verbb/feed-me#164]
This is a bit more complex, but I think it would be handy if the feed progress URL was distinct from the URL that triggers the import (if I've understood that correctly). That makes triggering an import a bit more deliberate, and long running imports forgotten in their own tab wont be accidentally triggered (*ahem*) :) 

I guess it's a POST v GET thing - having a URL to trigger the import is obviously good for cron-triggered imports, so I understand if the tradeoffs are better for the current setup.

**Comment by engram-design** [comment]
So to clarify - you'd want the Direct Feed link icon to not run the feed, instead present you with a link that does run the feed (to copy/paste into a Cron Job for example).

**Comment by ldstevens** [comment]
Thinking aloud...

To me it might make a bit more sense to have a third "run" screen in the feed flow which doesn't trigger the import automatically, i.e.
1. Metadata [exists]
2. Field mapping [exists]
3. Run/Status

The status page would have a button that would POST to start the import, and then be disabled while the progress bar appears, and then would have success/fail info. But refreshing the page wouldn't start an import itself. 

"Run task" could be the same functionality on the Index page, but would leave you on that page, so you could trigger feeds there without switching screens.

The "Direct Feed" icon on the index table would take you to the status page, but you'd have to click to run. An actual direct feed for cron jobs would be a separate URL you would copy and paste from the metadata (?) screen perhaps?

This would be a significant flow/UI change though, so I understand if you'd rather not tackle it now!

**Comment by ldstevens** [comment]
...and just to add: this would be handy when you have long-running imports but don't want to keep the progress page open, i.e. you could return to the "3. Run/status" to check in on progress without affecting the import itself. (To me that's a bit easier than scrutinising the CP sidebar task bar.) ✌️

**Comment by engram-design** [comment]
Agree with all that, and will likely address in 2.1. Great to get your feedback when thats implemented to see if it flows well.

**Comment by engram-design** [comment]
Added to the [latest master](https://sgroup.com.au/plugins/feedme/download).
