### ISSUE TITLE
craft cp unresponsive when starting run task

### ISSUE THREAD

**Issue by rolfkokkeler** [verbb/feed-me#219]
After a 'run task' the craft cp is becoming unresponsive.
I have to close Chrome completely and open the craft cp again.
Then it's fine, I can access all parts of the craft cp again.

I'm on OSX 10.12.4, Chrome Version 58.0.3029.110 (64-bit), Craft 2.6.2980 and Feedme 2.0.5

**Comment by engram-design** [comment]
Can you try another browser while the task is being run - can you access the CP from there?

**Comment by rolfkokkeler** [comment]
Just started a task in Firefox 53.0.2 (64-bits).
CP unresponsive.
I started the CP in Chrome, all is well.

**Comment by howells** [comment]
I have the same problem, with Feedme 2.0.7. I can start the task in Chrome, but then CP won't work at all. However if I open it in Safari, it works fine.

**Comment by grafixgeek** [comment]
I confirm the same as @howells for me. On small tasks it doesn't seem to matter as much, but on larger ones with thousands of entries Chrome won't open the CP, even in new tab, or after closing. Safari fine while job is processing.

**Comment by engram-design** [comment]
This has been improved a little as of the [latest master](https://sgroup.com.au/plugins/feedme/download), but there are still some cases where it'll hang. This actually come down to one of Craft's underlying functions, and am investigating what (if anything) we can do to get around this.

**Comment by justcookin** [comment]
Has there been any more insights as to what might be causing this? I am seeing it with some imports but its intermittent.

**Comment by engram-design** [comment]
This should be addressed properly in [2.0.10](https://verbb.io/craft-plugins/feed-me/download?v=2).
