### ISSUE TITLE
Tons of "Could not delete the file..." errors in craft.log

### ISSUE THREAD

**Issue by lindseydiloreto** [verbb/feed-me#226]
When I'm importing images, I get a ton of lines like this in `craft.log`...

    [error] [application] Could not delete the file /craft/storage/runtime/assets/thumbs/200/5799.jpg because the file does not exist.
    [error] [application] Could not delete the file /craft/storage/runtime/assets/sources/5799.jpg because the file does not exist.

    [error] [application] Could not delete the file /craft/storage/runtime/assets/thumbs/200/5806.jpg because the file does not exist.
    [error] [application] Could not delete the file /craft/storage/runtime/assets/thumbs/60/5806.jpg because the file does not exist.
    [error] [application] Could not delete the file /craft/storage/runtime/assets/sources/5806.jpg because the file does not exist.

Sometimes it's only two errors together (`thumbs/200` & `sources`), but sometimes a third error is included (`thumbs/60`).

**The good news,** it looks like my images are being imported as desired! I just can't figure out why the `craft.log` is littered with these "Could not delete" errors.

**Comment by engram-design** [comment]
Have you indexed your assets lately? What import strategy do you have setup for you feed? Are you uploading your assets, or just matching them?

**Comment by lindseydiloreto** [comment]
@engram-design This totally fell through the cracks, and now it's been ages since it happened. In summary, I have no idea. 😉 

I'm gonna close this thread, as it's now meaningless to both of us. Thanks!
