### ISSUE TITLE
Cannot import data containing < or >

### ISSUE THREAD

**Issue by terryupton** [verbb/feed-me#233]
I have a couple of fields that contain the < > symbols. As an example;
"origin mark":"<YALONG>",

It seems these are not imported and fail. Is there anyway to get around this? Unfortunately they cannot be removed from the original data.

**Comment by engram-design** [comment]
@terryupton Can you provide a bit more information? What sorts of fields are you trying to import this into? Can you provide a short snippet of example feed (XML/JSON)?

**Comment by terryupton** [comment]
Hi @engram-design - I was trying to import this into a plain text field within Craft.
Ultimately, I have got around this by changing this to a &gt; and &lt;
Is there a way I can share the original data sample without posting it publicly?

**Comment by engram-design** [comment]
@terryupton Sure, best to catch me on Slack sometime - handle `@crawf`
