### ISSUE TITLE
Add Limit and Offset to feed options

### ISSUE THREAD

**Issue by engram-design** [verbb/feed-me#243]

**Comment by engram-design** [comment]
This has been implemented in [3.0.0-beta.1 for Craft 3](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.1), through `limit` and `offset` parameters.

**Comment by engram-design** [comment]
Can you tell me how you're trying to use the parameters? You should be able to append it to the debug or direct feed URLs. For instance:

http://feedme.test/actions/feed-me/feeds/run-task?direct=1&feedId=1&passkey=b9JMx3rywl&limit=5&offset=10

**Comment by klick** [comment]
Hi Josh. So, it’s an url parameter?

I’m calling it in the templates like so:

```
{% for entry in craft.feedme.feed({
	    url: 'https://feedme.test/resources/test.json',
	    type: 'json',
	    element: '',
	    cache: 5,
	    limit: 1,
	}) %}

…
```

It should be `https://feedme.test/resources/test.json?limit=5` ?

**Comment by engram-design** [comment]
Ah, my apologies, I didn't realise you were using the template functions. This has been added in [3.0.0-beta.23](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.23).
