### ISSUE TITLE
Import pinboard rss — Categories have a space as separator

### ISSUE THREAD

**Issue by davidhellmann** [verbb/feed-me#252]
I try to import a pinboard.in RSS Feed but they have no separator like a comma. Just a space but when I import the tags into categories he do this:

Data:
tagA tagB tagC

he create just one category: tagA tagB tagC

Any chance to say whats the separator or another workaround?

**Comment by engram-design** [comment]
This isn't possible with Feed Me at the moment. Your only option is to write a script to pre-process this data, and then output it for Feed Me to import it.

We have plans in the future to implement these sorts of hooks for certain fields to implement your own logic. You could create your own `BaseFeedMeFieldType` that extends from `CategoriesFeedMeFieldType` with your own custom logic.

**Comment by ldstevens** [comment]
Late to this one, but you can actually use Feed Me & Craft to transform your data [in a Craft template](https://sgroup.com.au/plugins/feedme/feature-tour/using-in-your-templates) first (i.e. not importing), and then run the actual import against your new feed.

Twig gives you most of PHP's tools to do what you need to do, e.g. explode a value into an array, then loop through and add commas, etc.

**Comment by engram-design** [comment]
@ldstevens Not a bad idea, it does require a bit of DIY, but more than happy to post some example code

**Comment by engram-design** [comment]
This has been improved in Feed Me 3.x.
