### ISSUE TITLE
Task - Undefined variable: element

### ISSUE THREAD

**Issue by lboaretto** [verbb/feed-me#263]
error_reporting | Undefined variable: element
-- | --
line | 229
code | 8
file | /home/forge/site/craft/plugins/feedme/services/FeedMe_ProcessService.php

**Comment by engram-design** [comment]
Are you able to submit a Help request through the Feed Me plugin? We'll need some additional information to assist with debugging this issue.

**Comment by lboaretto** [comment]
Done.

**Comment by engram-design** [comment]
Fixed in [2.0.10](https://verbb.io/craft-plugins/feed-me/download?v=2).
