### ISSUE TITLE
Feed import tasks sat as 'pending'

### ISSUE THREAD

**Issue by adamhopkinson** [verbb/feed-me#264]
My feeds have been importing without issue for some time (although manually rather than scheduled). Now, when I try to run the task it sits as 'pending' ad infinitum - but isn't ever marked as 'stalled'. It looks a lot like #97 but on current versions.

### Additional info

- Plugin version: 2.0.7 (Pro)
- Craft version: 2.6.2994

**Comment by adamhopkinson** [comment]
Bizarrely, since updating the plugin to 2.0.7, when I click 'run' on a feed, it redirects to `/admin/feedme/feeds/run/1` rather than running as an AJAX request. Task is still sat as pending though.

**Comment by engram-design** [comment]
This should be addressed properly in [2.0.10](https://verbb.io/craft-plugins/feed-me/download?v=2), but let me know if you're still having issues.

I don't suppose you had the config settings `runTasksAutomatically` set to false?

**Comment by adamhopkinson** [comment]
Fixed in https://github.com/verbb/feed-me/commit/6a668979691b776a3bb702cb1d3d1fb36f8dc9bb #
