### ISSUE TITLE
Max backups on running of feed

### ISSUE THREAD

**Issue by espensgr** [verbb/feed-me#265]
### Description
I had setup a cron job that ran every hour and made a db backup every time, and that accumulated too 30 gb of backups. It would be nice to have a setting to set a max numbers of backups to prevent this kind of buildup.

### Steps to reproduce

1. Make a feed
2. Turn on backup
3. Run a cronjob every hour

### Additional info
- Plugin version: 2.0.7
- Craft version:  2.6.2994

I have the pre Verbb version, the new version failed so i couldn't use it, so i dont know if this is handled in the Verbb version

**Comment by engram-design** [comment]
We've added this in [2.0.10](https://verbb.io/craft-plugins/feed-me/download?v=2). Its controlled by a config setting `backupLimit`, but is by default set to 100. See https://verbb.io/craft-plugins/feed-me/docs/get-started/configuration
