### ISSUE TITLE
Null/false expiration dates import as current time

### ISSUE THREAD

**Issue by domstubbs** [verbb/feed-me#266]
Currently the postDate and expiryDate values are set with the following code:

````php
case 'postDate':
case 'expiryDate';
    $dateValue = FeedMeDateHelper::parseString($dataValue);

    // Ensure there's a parsed data - null will auto-generate a new date
    if ($dateValue) {
        $element->$handle = $dateValue;
    }
````

The `parseString` method returns a date for anything other than an empty string, so if postDate or expiryDate are false or null they will be saved with the current time. With expiry dates this is not so helpful. I’m not that familiar with the plugin yet but I’ve swapped the `$dateValue` assignment with the line below and it’s fixed date processing for the feed I’m working with.

````php
$dateValue = $dataValue ? FeedMeDateHelper::parseString($dataValue) : '';
````

### Additional info

- Plugin version: 2.0.9
- Craft version:  2.6.2997

**Comment by engram-design** [comment]
Fixed in [2.0.10](https://verbb.io/craft-plugins/feed-me/download?v=2).
