### ISSUE TITLE
Feed Me is not licensed

### ISSUE THREAD

**Issue by spoeken** [verbb/feed-me#267]
### Description

Hi, I get a message in logs saying [taskname]: Feed Me is not licensed.
even tho I have a license. 

It looks like it stops after I've refreshed the license page in settings. 

We've had some toubles with products not updating from an API, and I wonder if this is to blame. Will Feed Me finish the task even if it's unlicensed?

### Additional info

- Plugin version: Feed Me 2.0.7 (Pro) 
- Craft version: Craft CMS 2.6.2985

**Comment by engram-design** [comment]
You will likely need to update to 2.0.9, as licensing has changed over from S. Group to Verbb (different servers - in particular a faster one). Feed Me caches the licensing to a degree, but thats correct that it'll stop working if licensing fails.

**Comment by spoeken** [comment]
Ok, thank you. I've updated and hope that is the end of it. Makes sense at least.
