### ISSUE TITLE
Default entry status ignored

### ISSUE THREAD

**Issue by thijswhitespace** [verbb/feed-me#270]
### Description

When the option to import status is set to `Don't Import`, the status of entries is set to `enabled`, rather than the section's selected option for Default Entry Status.

### Steps to reproduce

1. Set the Default Entry Status of a section to `disabled`.
2. Setup an import for the section. On the fields option screen, set the Status option to `Don't Import`.
3. Import data into the section.

### Additional info

- Plugin version: 2.0.9
- Craft version: 2.6.2997

**Comment by engram-design** [comment]
This should be fixed in [2.0.10](https://verbb.io/craft-plugins/feed-me/download?v=2).
