### ISSUE TITLE
Null expiry dates don't overwrite existing expiry dates

### ISSUE THREAD

**Issue by ldstevens** [verbb/feed-me#272]
Hey Josh!

I'm running 2.0.11 and ran into an issue similar to #266. I have a JSON feed being imported to update existing entries. These entries have expiry dates, and I want to remove them by importing a null value for the expiry date field. 

In EntryFeedMeElementType.php there is currently:
```php
case 'postDate':
case 'expiryDate';
$dateValue = FeedMeDateHelper::parseString($dataValue);

// Ensure there's a parsed data - null will auto-generate a new date
if ($dateValue) {
  $element->$handle = $dateValue;
}
```

The update in 2.0.10 means `FeedMeDateHelper::parseString` will return a null value if $dateValue is indeed null, but the following conditional that checks if $dateValue is truthy prevents that null value being used to update the element. 

AFAICT removing the conditional solves the problem, but I'm not sure what the side effects are.

Cheers :)

**Comment by engram-design** [comment]
I'd say you're actually right on this - that was before we'd added a bunch of refactoring into that date helper, which should address this anything.

Updated in the [latest master](https://verbb.io/craft-plugins/feed-me/download?v=2)
