### ISSUE TITLE
mb_convert_case() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by alexmglover** [verbb/feed-me#276]
### Description

I am importing an XML feed, and the slugs are being passed into toLowerCase as an array, causing the error `mb_convert_case() expects parameter 1 to be string, array given`.

### Steps to reproduce

1. Import an XML feed of entries, making sure to associate the slug item from the XML feed to the slug field on the entry.
2. Click the FeedMe debug button on the feed. The error above is shown.

### Additional info

- Plugin version: 2.0.11
- Craft version: 2.6.2999

**Comment by engram-design** [comment]
I believe we may have followed this up via Slack. Are you still having issues with this?

**Comment by alexmglover** [comment]
I’m not, thanks! If I remember correctly, I had chosen the incorrect feed type, but I’m not 100% sure.

**Comment by engram-design** [comment]
Sure, do feel free to re-open this issue (or get in touch via Slack) if this comes up again.

**Comment by akukral** [comment]
I cannot seem to find the solution for this in Slack. I have my feed setup properly as XML and am getting the same issue. Would you mind pointing me to the thread in Slack or posting the solution here?

**Comment by alexmglover** [comment]
In my case I had chosen Atom instead of RSS or vice versa. I had to try the different types and one worked.

**Comment by akukral** [comment]
Actually was just about to post my findings: My issue was that when selecting the primary element for my XML feed I selected was the outer most XML tag and not the tag for the individual listings.

**Comment by fantasticmachine** [comment]
It would be **super** useful if the solution to this issue could be published here. Any Slack conversation is long gone. I'm running into it and can't find any information on what might be the cause (other than the comments here about incorrect format and primary elements - neither of which are the cause for me).

**Comment by alexmglover** [comment]
I believe I mentioned my issue previously in the thread but it was because I chose the wrong type for my feed when creating it.

**Comment by fantasticmachine** [comment]
I take it back. That stopped the error but still won't import anything.

**Comment by fantasticmachine** [comment]
OK I remade my XML file. This time I made sure all tag names were lowercase... and I seem to have shaken off that error.

**Comment by engram-design** [comment]
@fantasticmachine FYI, this is a very generic error and it can be cause by a lot of different things. Typically, its when you try to import array data into a field that doesn't accept arrays. Like importing array content into a Plain Text field.

Often (as you've mentioned), it'll come down to a primary element issue.
