### ISSUE TITLE
When "Disable Elements" is only import srategy select feed is still creating new elements 

### ISSUE THREAD

**Issue by brettburwell** [verbb/feed-me#277]
### Description
I have a feed where I _only_ want to disable existing elements that are missing from the feed. The "Disable missing elements" checkbox is the only option selected under the "Import strategy" for the feed. 

When I run the feed it's still creating new elements. And on repeat runs it's actually creating duplicates of existing elements (when I'd expect it to only disable any missing elements). 

Is there a chance I hit a bug or am I just misunderstanding how this specific scenario should function?

### Additional info

- Plugin version: 2.0.9
- Craft version: 2.6.2990

**Comment by engram-design** [comment]
What field are you matching on to find existing elements, Title or other? Are you importing entries?

**Comment by engram-design** [comment]
This should be fixed in the [latest master](https://verbb.io/craft-plugins/feed-me/download?v=2) and will be rolled into the next release.

**Comment by brettburwell** [comment]
Hi Josh. That's fantastic news. My apologies that I didn't follow up faster on the questions from your original post. I got sidetrack with another site launching so this got pushed down my to-do list. 

But I very much appreciate you looking into this and following up.
