### ISSUE TITLE
Images not importing (On *some* feeds)

### ISSUE THREAD

**Issue by bymayo** [verbb/feed-me#279]
### Description

We've got an issue where images are not importing in to an Assets field when using a remote URL. We've imported 10 XML files (All formatted the same) and theres only 1 file that is not importing the images.

An example file would be:

`http://www.gateway-gallery.co.uk/wp-content/uploads/2017/10/Alan-Lowndes-An-Actor-1.jpg`

And the way this is stored in the XML is:

`<Image_URL>http://www.gateway-gallery.co.uk/wp-content/uploads/2017/10/Alan-Lowndes-An-Actor-1.jpg</Image_URL>`

There are no errors being thrown.

I can supply the XML file over Slack (Or email) if you need to.

### Additional info

- Plugin version: 2.0.11
- Craft version: Craft CMS 2.6.3012

**Comment by engram-design** [comment]
Just wanted to check in on this, still an issue?

**Comment by engram-design** [comment]
Ah, good to know! Closing for now, but happy to reopen if its a Feed Me issue.
