### ISSUE TITLE
Multiple categories as a default value

### ISSUE THREAD

**Issue by EmptyStreets** [verbb/feed-me#281]
Hello,

Is there a way to specify multiple categories as a default value during the import? I tried to use comma as a delimiter but it doesn't work. Single value / category do work. The categories itself are already created. Please advise.
![screen](https://user-images.githubusercontent.com/1551388/37559665-33dc0ac0-2a2a-11e8-953c-eea41ef8c1cc.png)

**Comment by engram-design** [comment]
This has been implemented in Feed Me 3.x.
