### ISSUE TITLE
XML date not mapping to Entry Post Date

### ISSUE THREAD

**Issue by brycekirk** [verbb/feed-me#282]
### Description
When I try to pull releaseDate from an XML file into an Entry's Post Date, I get the following error: Call to a member function format() on boolean. The line in question is in FeedMeDateHelper.php: return $dateObject->format('Y-m-d H:i:s');

I'm assuming it has to do with the format of releaseDate: Thu, 15 Mar 2018 09:00:00 -0600. Since I'm only pulling from this feed, can I just edit the date format in FeedMeDateHelper.php?

### Steps to reproduce

1. Map releaseDate from this feed http://arcresources.mediaroom.com/api/newsfeed_releases/get.php to an Entry's Post Date

### Additional info

- Plugin version: 2.0.11
- Craft version: 2.6.3013

**Comment by engram-design** [comment]
I'm unable to reproduce this actually. Running the Debug action results in:

```
[postDate] => Craft\DateTime Object
(
    [date] => 2018-03-15 20:00:00.000000
    [timezone_type] => 3
    [timezone] => Australia/Melbourne
)
```
Are you able to confirm with the [debug action](https://verbb.io/craft-plugins/feed-me/docs/support/troubleshooting/debugging)?

**Comment by brycekirk** [comment]
debug is how I got the errors in the first place, but it seems to be working now. I must have messed something else up before. Thanks!
