### ISSUE TITLE
Craft 3: Getting unknown property: verbb\feedme\records\FeedRecord::fieldElementMapping

### ISSUE THREAD

**Issue by Coysh** [verbb/feed-me#285]
### Description
When creating a new feed, I get the fatal error on both 'Save' and 'Save & continue'

`Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: verbb\feedme\records\FeedRecord::fieldElementMapping`

### Steps to reproduce

1. Create feed
2. Fill in information
3. Press Save

### Additional info

- Plugin version:

Feed Me | 3.0.0-beta.1
Feed Me Pro | dev-master
- Craft version: 3 RC17.1

**Comment by engram-design** [comment]
Can you run `composer require verbb/feed-me:dev-craft-3`?

**Comment by Coysh** [comment]
That worked fine. Thanks!
