### ISSUE TITLE
_createElement method on new Entries created as a subfield throws exception

### ISSUE THREAD

**Issue by bwlng** [verbb/feed-me#291]
### Description

When *Create new entries if they do not exist* is checked when importing into an *Entries* field, the import will fail because the `_createElement` method in `/src/fields/Entries.php` attempts to set a `groupId` instead of a `sectionId` & `typeId`.

Updating the `_createElement` method to use a `sectionId` from the `$sectionIds` array and adding the first type from that section allows the entry to save.

Related to #290, there isn't currently a UI that I'm aware of to select the section and entry type new entries should be assigned to, but if you are limiting your Entries field to a single section with a single type, you can work around it with the (hacky) code below:

```
    private function _createElement($dataValue, $sectionIds)
    {
        $element = new EntryElement();
        $element->title = $dataValue;
        $element->sectionId = $sectionIds[0]; // this will fail if the field's source is set to *All*
        $element->typeId = Craft::$app->sections->getEntryTypesBySectionId($sectionIds[0])[0]->id;

        if (!Craft::$app->getElements()->saveElement($element)) {
            throw new \Exception(json_encode($element->getErrors()));
        }

        return $element->id;
    }
```

### Additional info

- Plugin version: dev-craft-3
- Craft version: Craft CMS 3.0.1

**Comment by engram-design** [comment]
@bwlng This has been improved in [3.0.0.beta-5](https://github.com/verbb/feed-me/releases/tag/3.0.0.beta-5), and you'll also have the opportunity to select the section/entry type you want to add to.

For any other element type, the group its imported into is restricted by the fields' sources. Categories for instance can only have a single group - so new categories will be imported into that same group. Entries are however a little different in that you have two levels of structure - sections and types.

This will also adhere to any source restrictions you have on your field. You can only import into sources that your entry field is enabled for.
