### ISSUE TITLE
[v3] Unable to install plugin

### ISSUE THREAD

**Issue by hechtron** [verbb/feed-me#292]
### Description
I'm still unable to install plugin on fresh Craft 3 install with no other plugins installed.

### Steps to reproduce

1. Navigate to /manage/settings/plugins
2. Select install on the Feed Me plugin

### Additional info

- Plugin version: 3.0.0-beta.2
- Craft version: 3.0.1

PHP version 7.1.12
MySQL 5.6.38

**Comment by engram-design** [comment]
What's the error you're receiving? Do you have `devMode` on?

**Comment by hechtron** [comment]
Oh, apologies... I had put that in the other issue, apparently.

```
Error: An error occurred

Output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- symfony/console v3.4.7 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.1.12) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- symfony/console v3.4.7 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.1.12) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
- Installation request for symfony/console v3.4.7 -> satisfiable by symfony/console[v3.4.7].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
```

And yes, I'm in dev mode.

**Comment by engram-design** [comment]
Can you install any other plugins? Nothing in that error seems to point to a Feed Me dependancy at first glance

**Comment by hechtron** [comment]
Indeed... you're right. `composer update` (and beta 4) solved it. thx much.
