### ISSUE TITLE
Cannot install 3.0.0-beta.3

### ISSUE THREAD

**Issue by EmptyStreets** [verbb/feed-me#294]
composer require verbb/feed-me:^3.0.0-beta.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/csv 9.1.3 requires php >=7.0.10 -> your PHP version (7.2.3) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.1.2 requires php >=7.0.10 -> your PHP version (7.2.3) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.1.1 requires php >=7.0.10 -> your PHP version (7.2.3) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.1.0 requires php >=7.0.10 -> your PHP version (7.2.3) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.0.1 requires php >=7.0.10 -> your PHP version (7.2.3) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.0.0 requires php >=7.0.10 -> your PHP version (7.2.3) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - verbb/feed-me 3.0.0-beta.3 requires league/csv ^9.0 -> satisfiable by league/csv[9.0.0, 9.0.1, 9.1.0, 9.1.1, 9.1.2, 9.1.3].
    - Installation request for verbb/feed-me ^3.0.0-beta.3 -> satisfiable by verbb/feed-me[3.0.0-beta.3].

**Comment by Nordicdesign** [comment]
Same here, updating from beta 2 to beta 3. Local MAMP solo installation, just Feed me and redactor, CKeditor installed. 

==============

Error: An error occurred

Output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/csv 9.1.3 requires php >=7.0.10 -> your PHP version (7.2.1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.1.2 requires php >=7.0.10 -> your PHP version (7.2.1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.1.1 requires php >=7.0.10 -> your PHP version (7.2.1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.1.0 requires php >=7.0.10 -> your PHP version (7.2.1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.0.1 requires php >=7.0.10 -> your PHP version (7.2.1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - league/csv 9.0.0 requires php >=7.0.10 -> your PHP version (7.2.1) overridden by "config.platform.php" version (7.0) does not satisfy that requirement.
    - verbb/feed-me 3.0.0-beta.3 requires league/csv ^9.0 -> satisfiable by league/csv[9.0.0, 9.0.1, 9.1.0, 9.1.1, 9.1.2, 9.1.3].
    - Installation request for verbb/feed-me 3.0.0-beta.3 -> satisfiable by verbb/feed-me[3.0.0-beta.3].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by bartrylant** [comment]
Same here

**Comment by j-greig** [comment]
And here

**Comment by i2insights** [comment]
And here....  running a fresh install of Craft 3 and MAMP Pro

**Comment by engram-design** [comment]
This should be fixed running `composer require verbb/feed-me:^3.0.0-beta.4`.
