### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by joshworden** [verbb/feed-me#296]
### Description

Getting this error during feed creation process. Asset volumes are S3. 

Full stack trace: https://pastebin.com/xPbjHrjh

### Steps to reproduce

1. Create a feed
2. 

### Additional info

- Plugin version: 3.0.0-beta.4
- Craft version: 3.0.2

**Comment by bzin** [comment]
Having the same issue without having volumes on S3.

**Comment by joshworden** [comment]
I was able to bypass this error by adding return; to the very top of the getAssetLayoutByField($field) method in FeedMeVariable.php. Not ideal, and probably breaks some things, but it worked for my immediate purposes.

**Comment by texasbaptists** [comment]
I'm getting this same error with one csv feed import but have another working fine. I get as far as `/admin/feed-me/feeds/element/2` and the error shows up before I can map the fields `/admin/feed-me/feeds/map/2`.

**Comment by thisanimus** [comment]
I get this error when trying to import to an entry type that has a relation field to another entry.

**Comment by texasbaptists** [comment]
I removed the `entries` field and it worked also.

**Comment by thisanimus** [comment]
I also get the same error when importing to an entry type with tags.  It seems like it fails when it has to insert data into multiple tables.

**Comment by engram-design** [comment]
Fixed in [3.0.0.beta-5](https://github.com/verbb/feed-me/releases/tag/3.0.0.beta-5).
