### ISSUE TITLE
Unknown database 'craft' when selecting the database

### ISSUE THREAD

**Issue by Coysh** [verbb/feed-me#297]
### Description
When trying to run a feed, the backup of database fails.
The database Craft is using is a remote database, so I'm guessing mysqldump is trying to run on the local server.

`Import Members: The shell command "mysqldump --defaults-extra-file="/home/vagrant/sites/eauk-members/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --single-transaction --no-data --result-file="/home/vagrant/sites/eauk-members/storage/backups/feedme-180407_140002_tta1z1kedg.sql" craft && mysqldump --defaults-extra-file="/home/vagrant/sites/eauk-members/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --no-create-info --ignore-table=craft.craft_assetindexdata --ignore-table=craft.craft_assettransformindex --ignore-table=craft.craft_cache --ignore-table=craft.craft_sessions --ignore-table=craft.craft_templatecaches --ignore-table=craft.craft_templatecachecriteria --ignore-table=craft.craft_templatecacheelements craft >> "/home/vagrant/sites/eauk-members/storage/backups/feedme-180407_140002_tta1z1kedg.sql"" failed with exit code 2: mysqldump: Got error: 1049: Unknown database 'craft' when selecting the database - ShellCommandException.php:47`

### Steps to reproduce

1. Process feed

### Additional info

- Plugin version: dev-craft-3 (Pro: dev-master)
- Craft version: 3.0.2

**Comment by engram-design** [comment]
I believe this may be an issue with Craft itself, and is due to the backup option being selected. You could turn this off for the feed to prevent this issue? Have you tried running a normal backup through the Utilities?

**Comment by engram-design** [comment]
Closing for the moment, its related to core Craft database backups.
