### ISSUE TITLE
Importing Users doesnt listen to User Group selection

### ISSUE THREAD

**Issue by Harry-Harrison** [verbb/feed-me#299]
### Description
I'm using a trial of FeedMe Pro and when I'm doing in import with a CSV, I'm trying to use the default selection of a User Group but the import isn't setting the imported users to any group.

I'm also using multisite here, so that could be related though I can't test that. This happens regardless of if i select "All sites" or a single site on the first step of the import.

There's also no reported errors.

### Steps to reproduce

1. Import a set of users and assign a user group
2. See how they're not assigned to any user group

### Additional info

- Plugin version: 3.0.0-beta.4 & Pro beta.1
- Craft version: 3.0.2 Pro

**Comment by engram-design** [comment]
This is fixed in the latest code. Update via `composer require verbb/feed-me:dev-craft-3`, and will be bundled into the next release.
