### ISSUE TITLE
Lightswitch - Impossible to access an attribute ("type") on a string variable ("1")

### ISSUE THREAD

**Issue by bzin** [verbb/feed-me#301]
### Description

When a field Lightswitch is by default active on an Entry section, it does not allow to enter in the FeedMe mapping fields page. If Lightswitch is off the page opens fine.

https://pastebin.com/AC2UApU6

### Steps to reproduce

1. Create a section with a Lightswitch field that by default is active
2. Create a feed and try to import data into the Entry with the Lightswitch active
3. The mapping page does not open and gives the error:
`Impossible to access an attribute ("type") on a string variable ("1")`

### Additional info

- Plugin version: 3.0.0-beta.4
- Craft version: Craft Pro 3.0.2

**Comment by engram-design** [comment]
Fixed in [3.0.0.beta-5](https://github.com/verbb/feed-me/releases/tag/3.0.0.beta-5).
