### ISSUE TITLE
Multiple issues with entry Author field

### ISSUE THREAD

**Issue by eablokker** [verbb/feed-me#302]
### Description
New users are not created when importing entries and selecting "Create users if they do not exist".
Entries are not assigned the correct author when author already exists.

If "Full Name" is selected, the logs give an error of "Undefined index: query - Search.php:159".
I believe this could be due to Craft 3 having separate First Name and Last Name fields.

If "Username" is selected, the default value for Author is used.
I believe this could be due to Craft not allowing spaces in usernames.

If "Username" is selected, and username exists, the entry is created with the default Author instead of the correct author.

When creating new users in Craft, a dialog pops up asking to verify password. Feed Me does not pop up this dialog, so I believe there could be an issue where Craft needs to verify your password before Feed Me is able to create new users.

### Steps to reproduce

1. Set up a new feed using Entry element type
2. Select a field for the author, with a content of "Firstname LastName"
3. Choose "Data provided for this user is:" either "Username" or "Full Name"
4. Run Import

### Additional info

- Plugin version: 3.0.0.beta-4
- Craft version: 3.0.2

**Comment by engram-design** [comment]
Fixed in [3.0.0.beta-5](https://github.com/verbb/feed-me/releases/tag/3.0.0.beta-5).
