### ISSUE TITLE
Unable to save some field mappings

### ISSUE THREAD

**Issue by dbrookes** [verbb/feed-me#304]
### Steps to reproduce

1. Create JSON feed using the example json from the docs
2. Map fields to a Matrix field, hit save, mappings for matrix and some other fields are lost

### Description

Failing to save:

- Matrix fields
- Matrix enabled/collapsed (collapsed isn't in the post array)
- Default entry status also can't be saved, and the options don't match up with the new Craft 3 options?

Using the debugger I can see that the mapping never made it into the post request, and subsequently not into the database:

`$_POST fieldMapping -> /feed-me/feeds/map/13 `

```
    'sources' => [
        'field' => 'craft\\fields\\Matrix'
        'blocks' => [
            'source' => [
                'enabled' => '1'
                'fields' => [
                    'sourceTitle' => [
                        'field' => 'craft\\fields\\PlainText'
                        'node' => 'noimport'
                        'default' => ''
                    ]
                    'sourceUrl' => [
                        'field' => 'craft\\fields\\PlainText'
                        'node' => 'noimport'
                        'default' => ''
                    ]
                ]
            ]
        ]
    ]
```

### Additional info

- Plugin version: 3.0.0-beta.5 Pro
- Craft version: 3.0.3.1 Pro
- Browser: Chrome 66

**Comment by engram-design** [comment]
Seems strange, as things are working for me. Note that if you have `Collapsed` unchecked, it won't be in the POST request - so that's normal.

I _wonder_ if it might be a `max_input_vars` issue, if parts of the POST request are being lost? Failing that, if you can submit a Help request via the plugin?

**Comment by dbrookes** [comment]
I think figured it out, if you have a relationship field pointing at the same section you're importing into, then it overrides the initial mappings because the field names are the same, and you can't disable it.

For example:

If I have a section called `blog`, and it has a matrix field `sources` as above, and a related entries field `relatedBlogs` limited to `blog` section entries only).

Then since `relatedBlogs` contains `sources` as a field to import as part of the relationship, is it possible that it is overriding the original `sources` in the array so I end up posting `'node' => 'noimport'` since it was mapped after the original `sources`- even though it was never set to import `sources` the fields within the `relatedBlogs` relationship? (unchecking the enabled box doesn't prevent this situation)

If I remove `relatedBlogs` then I'm able to save the mappings for `sources` correctly, although collapsed didn't seem to work if I looked at the entry.

**Comment by engram-design** [comment]
Ah yes, there should actually be much tighter restrictions on allow sub-element fields for reasons like this (and more). This should now be fixed in the latest version, along with collapsed Matrix fields not being set.
