### ISSUE TITLE
Actual error message not showing up, getting session_start() instead

### ISSUE THREAD

**Issue by jonXmack** [verbb/feed-me#308]
### Description

I'm getting the error `session_start(): Cannot send session cookie - headers already sent by (output started at /Users/***/Sites/***/vendor/yiisoft/yii2/web/Response.php:414) - Session.php:137` when trying to import my feed, and I'm not sure at what point of the import it's causing the error. It will import some of the entries, but when it fails I just get that, so I'm having a hard time debugging the issue.

EDIT: I've just done some additional debugging by going through and disabling each field mapping one by one and it seems to be related to the importing/updating of matrix fields. However, I'm able to run the debug successfully with all the fields mapped.

### Additional info

- Plugin version: 3.0.0-beta.9
- Craft version: 3.0.4

**Comment by engram-design** [comment]
@jonXmack This is actually an issue with Craft itself, and only when running through the control panel and the queue system. The debug running isn't effected.

FYI, this should be fixed in the next Craft version - https://github.com/craftcms/cms/issues/2821
