### ISSUE TITLE
Feed not updating entries

### ISSUE THREAD

**Issue by buitbybrad** [verbb/feed-me#309]
### Description
We have an xml file which imports with no issues when creating new entries. When we try run the feed again with an updated xml file with some updated information (just some entries updated) entries do not get updated. We need to delete all entries and import again to get updated data into the CMS.

We're using an import id as the unique identifier which does not change between imports.

Here is our log when we rerun the import:

<img width="1113" alt="screen shot 2018-05-01 at 18 09 34" src="https://user-images.githubusercontent.com/38889876/39483613-e1d256c6-4d6a-11e8-8ed0-730b50060bf3.png">

The imported file is around 6mb

### Additional info

- Plugin version: 3.0.0-beta.9
- Craft version: 3.0.4

**Comment by engram-design** [comment]
This should be fixed in the latest Craft release. See also https://github.com/verbb/feed-me/issues/308
