### ISSUE TITLE
Implement third-party field support

### ISSUE THREAD

**Issue by engram-design** [verbb/feed-me#310]

**Comment by engram-design** [comment]
https://github.com/verbb/feed-me-helpers/issues/5
https://github.com/doublesecretagency/craft-smartmap/issues/6

**Comment by lindseydiloreto** [comment]
Thanks @engram-design, you're a champ! Let me know if you need any help with the Smart Map integration.

<img src="https://m.popkey.co/404132/xM35K.gif">

**Comment by bzin** [comment]
Do you have prediction when you guys will work on this @engram-design ?

Thanks

**Comment by engram-design** [comment]
Can't give you a firm timeframe (as there's a lot to test), but expect around a week.

**Comment by bzin** [comment]
Let me know if you need help on testing; I need integration with Smart Map badly. :)

**Comment by engram-design** [comment]
Added in [3.0.0-beta.12](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.12)

**Comment by Moorst** [comment]
Any timeframe on adding support for Solspace Calendar?
