### ISSUE TITLE
Auto created categories with a "," in the title, result in duplicates being created

### ISSUE THREAD

**Issue by marcushouse** [verbb/feed-me#312]
### Description
Some categories in our feed data had a comma in the category title (e.g. "Boutique, Handmade & Markets"). We ended up with many duplicate categories whenever it attempted to auto-create the category.

### Steps to reproduce

Have a "," in a category title being auto-imported (see screenshot)
![image](https://user-images.githubusercontent.com/298295/39501913-db535c5a-4e00-11e8-96b6-7eee4301fae1.png)

- Plugin version: 3.0.0-beta.9
- Craft version:  3.0.5

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.10](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.10)
