### ISSUE TITLE
Issue when importing XML

### ISSUE THREAD

**Issue by michtio** [verbb/feed-me#317]
### Description

When trying to import an XML file there is a PHP error showing:

`count(): Parameter must be an array or an object that implements Countable`

### Steps to reproduce

1. import the following XML file: https://staging.bouwjobs.be/example.xml

### Additional info

- Plugin version: 3.0.0-beta.9
- Craft version: 3.0.5

**Comment by engram-design** [comment]
I believe this is an issue with PHP 7.2 https://github.com/verbb/feed-me/issues/311.

**Comment by michtio** [comment]
@engram-design could be, but I'd love to see a quick fix for this :)

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.12](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.12)
