### ISSUE TITLE
Documentation for installing feed-me on Craft 3 via composer?

### ISSUE THREAD

**Issue by colinwilson** [verbb/feed-me#319]
Where are the docs for installing feed-me via composer on Craft 3 (v3.0.5)?

**Comment by engram-design** [comment]
Docs are forthcoming, but as per our [Blog Post](https://verbb.io/blog/feed-me-for-craft-3):

`composer require verbb/feed-me:^3.0.0-beta.1 verbb/feed-me-pro`

**Comment by colinwilson** [comment]
Thank you.
