### ISSUE TITLE
Parent category not created

### ISSUE THREAD

**Issue by colinmeinke** [verbb/feed-me#322]
### Description

When I import categories that have a parent category, the parent category is not created if it does not exist, even though the checkbox is ticked.

### Steps to reproduce

![](https://file-tysmqaduhd.now.sh)

The JSON looks like this https://trov-csv-to-json-xobrxqofwm.now.sh/products-ryTtrfoAG.json.

### Additional info

- Plugin version: beta-13 and pro 3.0.4

**Comment by colinmeinke** [comment]
Resolving this issue would convert us to paying users 😄

**Comment by engram-design** [comment]
Thanks, I'll check it out again, but our initial tests were working. Nothing in the logs?

**Comment by colinmeinke** [comment]
@engram-design there are logs of successful creation of the child category. It seems to just silently ignore the creation of the parent category.

```

Type | Message | Timestamp
-- | -- | --
info | Product Categories: Processing 1 elements finished in 0.53s | 5/22/2018 4:45 AM
info | Product Categories: Category 6715 added. | 5/22/2018 4:45 AM
info | Product Categories: Starting feed processing. | 5/22/2018 4:45 AM
info | Product Categories: Finished preparing for feed processing. | 5/22/2018 4:45 AM
info | Product Categories: Finished database backup | 5/22/2018 4:45 AM
info | Product Categories: Starting database backup | 5/22/2018 4:45 AM
info | Product Categories: Preparing for feed processing. | 5/22/2018 4:45 AM
```

**Comment by engram-design** [comment]
Aha, that'd be right, I was working on another branch that had this implemented as it was missing. If you're able to try the latest version (`composer require verbb/feed-me:dev-craft-3`)

**Comment by engram-design** [comment]
Added in [3.0.0-beta.14](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.14)
