### ISSUE TITLE
Support Craft/Yii Alias in Feed URL

### ISSUE THREAD

**Issue by craftedsystems** [verbb/feed-me#325]
### Description

I would like to use Craft/Yii aliases like `@storage` as part of the Feed URL.
For instance `@storage/imports/data.json` does not seem to work as expected.

**Comment by engram-design** [comment]
@craftedsystems What version are you on? It currently does support aliases - for instance `@web/file.json`

**Comment by craftedsystems** [comment]
I am using `3.0.0-beta.14` and I get this error when using the `@storage` alias.

```
Unable to reach @storage/imports/press.json. Message: sha1_file(/assets/cp/cp.js): failed to open stream: No such file or directory
```

**Comment by engram-design** [comment]
I've just tested this on my install and works a treat. That error message doesn't seem to be related to Feed Me - what is `/assets/cp/cp.js`? Not sure where `sha1_file(/assets/cp/cp.js)` is coming from?

**Comment by engram-design** [comment]
Hmmm, can't seem to reproduce this I'm afraid...

**Comment by craftedsystems** [comment]
Thx for trying

**Comment by engram-design** [comment]
Closing as I couldn't replicate. Happy to rope in @lindseydiloreto if its an issue, but chalking this up to environment issues.

**Comment by lindseydiloreto** [comment]
@engram-design Thanks for the ping.

@craftedsystems Interesting... `sha1_file` is definitely something that both CP CSS & CP JS use. I'm happy to take a look into the issue, would you mind opening a ticket on the `craft-cpjs` repo?
