### ISSUE TITLE
Import to Craft Products

### ISSUE THREAD

**Issue by bartrylant** [verbb/feed-me#327]
I want to import a feed with products into Commerce. According to https://verbb.io/craft-plugins/feed-me/docs/guides/importing-commerce-products/setup-your-feed I have to choose "Entry" as element type. However, this forces me to select a section and an entry type, which I don't have right now. I don't see how Commerce products are related to Entries at all.

Using
Craft edition & version | Craft Pro 3.0.9
Craft Commerce | 2.0.0-beta.5
Feed Me | 3.0.0-beta.14
Feed Me Pro | 3.0.4 (trial, not bought yet)

**Comment by pauljohnston** [comment]
I also don't see the option to select 'Products' Element Type and therefore can't import commerce products or commerce variants.

Using
Craft edition & version | Craft Pro 3.0.9
Craft Commerce | 2.0.0-beta.5
Feed Me | 3.0.0-beta.14
Feed Me Pro | 3.0.4

**Comment by engram-design** [comment]
Apologies for the confusion, Commerce support isn’t ready yet, but will be in the next week. Its our top priority and working on it now. Please let me know if you’ve purchased a license based on this assumption and we’ll happily refund. Its taken longer than we expected…

**Comment by bartrylant** [comment]
I was just using the trial version on a dev site right now to see how it would work, so no license bought yet.

**Comment by echantigny** [comment]
I'm also waiting to try this one.  Just sent you a note about it on your Contact Form on the website.  Found this right after.  Thanks

**Comment by keithmancuso** [comment]
Not to pile on but reall hoping to get this this week as we have a project we can’t finish without it!

**Comment by engram-design** [comment]
Added support in [3.0.0-beta.15](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.15).

**Comment by keithmancuso** [comment]
Thank you!!
