### ISSUE TITLE
Return URL incorrect when clearing logs

### ISSUE THREAD

**Issue by fantasticmachine** [verbb/feed-me#328]
### Description
When clicking to clear log files the return url appears to be incorrect.
It is redirecting to /feedme/logs instead of /admin/feedme/logs and thus lands on a 404 page

### Steps to reproduce

1. Go to Feedme control panel.
2. Click on logs tab
3. Click "Clear logs" button

### Additional info

- Plugin version: 2.0.11
- Craft version:  2.6.3016

**Comment by engram-design** [comment]
Fixed in [2.0.12](https://github.com/verbb/feed-me/releases/tag/2.0.12).
