### ISSUE TITLE
"0" string doesn't get recorded / imported by FeedMe

### ISSUE THREAD

**Issue by whoisjuan** [verbb/feed-me#329]
### Description

When you import an entry that has a text field and the imported text is a string of "0", FeedMe doesn't record/import the string. Other variations like "0.0" and "0.00" are indeed imported correctly.

### Steps to reproduce

1. Create an import job that has field text.
2. Import a JSON that maps to that field with string "0"
3. "0" doesn't get imported. The field text remains empty.

### Additional info

- Plugin version: 3.0.0-beta.14
- Craft version: 3.0.9

**Comment by engram-design** [comment]
Just testing this out, and your findings are indeed correct. However, I've just tried to save an entry with a plain text field via Entries > New entry, and its not saving a value when only "0" is entered. I have a feeling this may be a Craft issue and the Plain Text field type.

Are you able to confirm you can or cannot save an entry with "0" as the value of a plain text field?

**Comment by engram-design** [comment]
Reference - https://github.com/craftcms/cms/issues/2935

**Comment by whoisjuan** [comment]
You're right. This is a Craft issue. Thanks for looking into it.
