### ISSUE TITLE
Can’t assign default categories to feeds

### ISSUE THREAD

**Issue by onebrightlight** [verbb/feed-me#330]
### Description
I'm attempting to run a number of Feed Me imports for a client site and I find I can't assign a default category to any of the feeds, as seen here:

![4e0a09fb-efba-416a-a4e4-a05d099c32bc](https://user-images.githubusercontent.com/366427/40900507-b87a9286-6780-11e8-99f2-b1c5a1d394ff.png)

### Steps to reproduce

1. Create any feed to import in Craft 3 Feed Me plugin
2. Assign fields and locate a category field.
3. Choose "Use default value"
4. Notice there is no option to assign a default category for the feed

### Additional info

- Plugin version: 3.0.0 Beta 14
- Craft version: 3.0.9

**Comment by engram-design** [comment]
Added support in [3.0.0-beta.15](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.15).
