### ISSUE TITLE
Message: filemtime(): stat failed for filename.csv

### ISSUE THREAD

**Issue by skramstad** [verbb/feed-me#331]
### Description

When trying to set up a new feed in feed me pro, and Element Type User, I get the following error:
Message: filemtime(): stat failed for /home/someusername/source/storage/runtime/cache/a9/a9df6186e92a4650919db5dfc3f0fec6.bin

Earlier I got a error in twig saying something like cake utility hash, but that error got away after I cleared pending jobs and craft cms cache.

I've checked that the file exists.

I have not bought a license yet for feed me pro before I know its working.

### Steps to reproduce

1. Upload a .csv file
2. Set path to /home/someusername/source/import/filename.csv
3. Create a new feed and select Element Type User
4. Save & continue
5. error message

### Additional info
- Plugin Feed Me: 3.0.0-beta.14
- Plugin Feed Me Pro: 3.0.4
- Craft version: Craft Pro 3.0.9

**Comment by skramstad** [comment]
Ok. I disabled Freeform Lite and the problem disappeared. So there is something going on when Freeform Lite and Feed Me is activated.

Could you look into that and see if you can solve this.

Thanks!

**Comment by engram-design** [comment]
I'll continue to investigate, but can't seem to reproduce here. If you're getting an error with CakePHP, it might be worth uninstalling and reinstalling Feed Me.

**Comment by engram-design** [comment]
https://github.com/verbb/feed-me/issues/333

**Comment by skramstad** [comment]
Thanks @engram-design. I still get the same error. I tried to reinstall Feed Me + Feed Me Pro but no luck. I'll see if I can get some more data from the error.

**Comment by engram-design** [comment]
Sorry @skramstad I just can't replicate this one, I wonder if its a conflicting plugin issue, or some other environment setup? Internally, Feed Me doesn't even call the `filemtime()` function, and its pointing to a temporary cache file. As such, going to close it, but let me know if you want to continue debugging.
