### ISSUE TITLE
Class 'Cake\Utility\Hash' not found

### ISSUE THREAD

**Issue by raygers** [verbb/feed-me#333]
### Description
After setting up a new feed and clicking on save and continue I get the following error:
\Class 'Cake\Utility\Hash' not found

### Steps to reproduce

1. Setup new feed
2. Click on save and continue

### Additional info

- Plugin version: 3.0.0-beta.14
- Craft version: Craft Pro 3.0.10.1

I know that it is probably a missing library, but how do I install Cake? Via composer?

**Comment by engram-design** [comment]
How did you install Feed Me, through Composer or the plugin store? Cake's utilities are a requirement of Feed Me, and should be installed alongside Feed Me, so this seems strange.

**Comment by raygers** [comment]
@engram-design , thanks for the response. I installed the Feed Me plugin via the store from within Craft.

**Comment by engram-design** [comment]
Are you able to provide what other plugins you have installed? Maybe try uninstalling and reinstalling Feed Me? I would assume there's no `cakephp` folder in `/vendor`?

**Comment by raygers** [comment]
Thanks, I managed to resolve it by uninstalling the plugin and re-installing the plugin via the store.

Thanks for your assistance.
