### ISSUE TITLE
Can't set entry status.

### ISSUE THREAD

**Issue by oadslug** [verbb/feed-me#336]
### Description

I can't seem to figure out how to set the entry status, when creating (importing new) or updating an entry. I have tried every combination of data that I can think of: (i.e. 1, 0, enabled, disabled, true, false, empty string) — nothing seems to work. I am using an xml feed with an `<enabled>` node, and have selected that node for the 'Status' map dropdown (I have also tried every combination of the 'default' dropdown to the right of the map dropdown, however, once a field is mapped, the default drop-down value always reverts to 'Don't Import' when saved). Any help would be appreciated. Thanks.

### Additional info

- Plugin version: Feed Me Pro 3.0.4
- Craft version: Craft CMS 3.0.11

**Comment by eric-chantigny** [comment]
I'm having the same issue importing with a CSV file.

**Comment by ul8** [comment]
+1 
same issue here in CSV entry import (Craft Pro 3.0.12 feed Me Pro 3.04)

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.16](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.16).
