### ISSUE TITLE
User groups not updating properly

### ISSUE THREAD

**Issue by Coysh** [verbb/feed-me#338]
### Description
When a user already has a group (i.e. Level 1), and the import states they are in another group (i,e. Level 2), Feed Me does not remove them from a group before adding them to the new group.#

Should Feed Me remove the user from all groups, and then add them to the new groups?
Or should this be an option?

### Steps to reproduce

1. Create feed to import Users
2. Make sure the feed has a new user group the user isn't already in
3. Look at how Feed Me works, adding the new group to the user - but not removing them from previous

### Additional info

- Plugin version: 3.0.0-beta.15
- Craft version: 3.0.12

**Comment by engram-design** [comment]
That's correct behaviour. Any group that a user currently belongs to will still be kept after import. As such, it really just adds user groups to a user.

We will look at making this more configurable in the future.

**Comment by Coysh** [comment]
@engram-design that is a big pain for me, as a user's access is currently based on their group.
Any suggestions on how to get around this? This could mean me not using Feed Me at all :(

**Comment by Coysh** [comment]
@engram-design Hey Josh, this is make or break with me whether to purchase Feed Me. Any suggestions on how to get around it?

**Comment by engram-design** [comment]
I'll look at making this a config setting as soon as I can. Unfortunately, people want to be able to have both options available to them!

**Comment by engram-design** [comment]
I've added this as an option in field mapping. This will be in the next release.
<img width="444" alt="screen shot 2018-08-15 at 10 14 09 pm" src="https://user-images.githubusercontent.com/1221575/44147725-98c311fc-a0d8-11e8-8680-7a266e03b187.png">
