### ISSUE TITLE
'Run Feed' link redirects to homepage after starting feed import

### ISSUE THREAD

**Issue by oadslug** [verbb/feed-me#341]
### Description

When attempting to run an import using the "Run Feed" or "Start Processing Feed" links , the browser is redirected to the site homepage (i.e. `http://testsite.craft3.dev/admin/feed-me/feeds/run/4` redirects to `http://testsite.craft3.dev/`). However, the feed import process does start. I can only guess that perhaps there is an error in the route?

### Additional info

- Plugin version: Feed Me 3.0.0-beta.15, Feed Me Pro 3.0.4
- Craft version: Craft CMS 3.0.11

**Comment by engram-design** [comment]
Strange, it calls `$request->getReferrer()` to redirect back to the URL it was being called from. It seems like this is empty in your case, but through testing on my end, its certainly correct.

I don't suppose there's any insight you can give with regards to your setup or browser?

**Comment by engram-design** [comment]
Should be fixed in [3.0.0-beta.17](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.17).

**Comment by oadslug** [comment]
Confirmed fixed. Thanks!
