### ISSUE TITLE
'Use default value' not working with drop-down fields

### ISSUE THREAD

**Issue by oadslug** [verbb/feed-me#343]
### Description

The 'Use default value' for Feed Element does not appear to be working with user-defined drop-down fields (and perhaps other fields as well) — at least when importing using an XML feed (haven't tested other feed types).

### Steps to reproduce

1. Set 'Feed Element' drop-down to "Use default Value" (on a user-defined field).
2. Set 'Default Value' drop-down to the value you would like to set (i.e. "Dark").

### Additional info

- Plugin version: Feed Me 3.0.0-beta.15, Feed Me Pro 3.0.4
- Craft version: Craft CMS 3.0.11

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.16](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.16).

**Comment by oadslug** [comment]
Works for me. Thanks again!
