### ISSUE TITLE
Multisite Import from 2 different site feeds. Entries get assigned to all sites

### ISSUE THREAD

**Issue by john-henry** [verbb/feed-me#345]
### Description
Using 2 different feeds assigned to 2 separate sites. After each import, all entries end up with 2 sites enabled. 

### Steps to reproduce

1. Created 2 separate feeds for same Channel
2. Assign a different site for each feed
3. Import each feed separately
4. Viewing Channel shows all entries assigned to both sites

### Additional info

Original feeds have no crossover of entries

- Plugin version: 3.0.0-beta.15
- Craft version: Craft CMS 3.0.12

**Comment by engram-design** [comment]
Just a quick one - what is your section setup like? I assume you have `Propagate entries across all enabled sites?` un-checked?

**Comment by john-henry** [comment]
Hi @engram-design 

I have 1 Structure section called Products.
2 sites. Each site has its own products to import. So 2 different feeds

Now here is a weird one. `Propagate entries across all enabled sites?` setting only appears for for a Channel section. Mine is a Structure section and that setting does not appear.

**Comment by engram-design** [comment]
@john-henry Gotcha, I'm debating on the best approach here. If you were to create an entry in the structure for say Site 2, it would automatically be created for Site 1 - correct? That's all just through the CP saving as normal. You then have the option to disable the entry on one site or the other, but I don't believe you can plain delete it without deleting it from both sites?

Anyway, I've put a solution together to prevent entries from propagating to other sites in the next release.

**Comment by dominikkrulak** [comment]
Has a solution been implemented yet? Just today I came across this issue, well it's not the issue, more like enhancement.
