### ISSUE TITLE
Can't assign default value to elements field

### ISSUE THREAD

**Issue by exophunk** [verbb/feed-me#346]
### Description

I'm importing a csv file and I want to set a elements field to a fixed default value.

![grafik](https://user-images.githubusercontent.com/4455472/41918965-b1c93d40-795d-11e8-86dc-08818a8fe2e4.png)

I simply want to set the "slug" of the field to a fixed value, so every imported entry is then related to the same entry. But I can't as no input field shows up for "Default Value".

I think this is similar to https://github.com/verbb/feed-me/issues/330

Am I doing something wrong or can you enable defaults for element fields?

### Steps to reproduce

1. Create any feed to import in Craft 3 Feed Me plugin
2. Assign fields and locate a elements field.
3. Choose "Use default value"
4. Notice there is no option to assign a default category for the feed

### Additional info

- Plugin version: 3.0.0-beta.15
- Craft version: 3.0.12

**Comment by engram-design** [comment]
Added in [3.0.0-beta.16](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.16).
