### ISSUE TITLE
Class 'verbb\feedme\elements\BaseHelper' not found - CommerceProduct.php:343

### ISSUE THREAD

**Issue by anchovy** [verbb/feed-me#350]
### Description
Importing into commerce products (feed-me-pro) via CSV if you select 'Use Default' for say `Available for Purchase` and check the checkbox for the default value on processing the feed the the following error is generated:

> NAME_OF_IMPORT: Class 'verbb\feedme\elements\BaseHelper' not found - CommerceProduct.php:343

### Steps to reproduce

1. Create new import
2. Select Use Default for `Available for Purchase`
3. Check checkbox
4. complete additional settings
5. Save & run import
6. View logs.

### Additional info

- Craft Commerce: 2.0.0-beta.5
- Feed-Me-Pro:  3.0.4
- Feed-Me: 3.0.0-beta.15
- Craft version: Craft Pro 3.0.11

### Fix
Add `use verbb\feedme\helpers\BaseHelper;` at line 10 to the file `/vendor/verbb/feed-me/src/elements/CommerceProduct.php`

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.16](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.16).
