### ISSUE TITLE
'trim() expects parameter 1 to be string, array given - PlainText.php:140' in particular JSON file

### ISSUE THREAD

**Issue by whoisjuan** [verbb/feed-me#359]
### Description
I'm using FeedMe to import some entries dynamically. I always pass it the same JSON format and 95% of the times I get a successful processing of the items. However, sometimes I get this error:

`trim() expects parameter 1 to be string, array given - PlainText.php:140 in particular JSON file`

Here is a URL with a JSON that triggers that error:
https://s3-us-west-2.amazonaws.com/waveguideio/JSON-Records/recordLP2018-07-23+06%3A56%3A23.json

And here is another URL with a similar JSON that doesn't trigger that error:
https://s3-us-west-2.amazonaws.com/waveguideio/JSON-Records/recordLP2018-07-23+07%3A11%3A37.json

### Steps to reproduce

1. Similar JSON files to import entries.
2. Process file 1, error. 
3. Process file 2, no error.
4. No practical difference in the files, so the reason of the error in unknown.

### Additional info

- Plugin version: 3.0.0-beta.17
- Craft version:  3.0.16.1

EDIT: Here is another random JSON file that is failing with the same trim() error: https://s3-us-west-2.amazonaws.com/waveguideio/JSON-Records/recordLP2018-07-23+23%3A41%3A16.json

**Comment by whoisjuan** [comment]
It seems that trim() has some trouble with certain special characters. I fixed this issues by sanitizing the strings that were causing the issue.

**Comment by thisisjamessmith** [comment]
Just leaving a note here, probably for my future self, that this error occurs when the import content destined for a plain text field contains a pipe character, presumably because FeedMe is trying to dynamically split the string as it does for category lists.
