### ISSUE TITLE
XML file Unable to match an existing element

### ISSUE THREAD

**Issue by CreateSean** [verbb/feed-me#364]
### Description

When running an XML import to entries it runs and appears to be successful, but no entries are added and when looking at the logs I see this.

The Word For You Today: Processing 0 elements finished in 0.00s | 8/1/2018 11:50 AM
-- | --
error | The Word For You Today: Unable to match an existing element. Have you set a unique identifier for ["title"]? Make sure you are also mapping this in your feed and it has a value. - Element.php:110

I do have a title being mapped and it is set to be the unique identifier

### Steps to reproduce

1. upload xml file
2. run feed

### Additional info

- Plugin version: 3.0.0-beta.17
- Craft version: 3.0.17.1

**Comment by engram-design** [comment]
I'd probably need a bit more information on your feed setup. Are you able to send through a support request through the plugin?

**Comment by CreateSean** [comment]
Josh, 

message sent with all attachments. Hope this helps.

**Comment by engram-design** [comment]
Solved. Additional XML elements with no data in `<title>` and incorrect primary element were the cause.
