### ISSUE TITLE
Craft 3 & Solspace Calendar

### ISSUE THREAD

**Issue by Moorst** [verbb/feed-me#370]
Is there a plan to support Solspace Calendar with Feed Me Pro for Craft 3?

I know there was a helper available for Craft 2 (https://github.com/verbb/feed-me-helpers/tree/master/calendarhelper) and there has been some progress in adding support for other third-parties such as Smart Map.

**Comment by engram-design** [comment]
There is a plan, the helpers from Craft 2 will be imported before Feed Me 3 is out of beta. No ETA but shouldn't be too far off.

**Comment by keithmancuso** [comment]
Would love to see this sooner than later if possible, we have a project stalled waiting for it.

**Comment by engram-design** [comment]
Added in Feed Me [3.0.0-beta.23](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.23) for Craft 3.

**Comment by keithmancuso** [comment]
Thanks sooooooo much! Perfect timing!
