### ISSUE TITLE
Ability to set 'isActive' status on variants

### ISSUE THREAD

**Issue by oadslug** [verbb/feed-me#372]
### Description

Feature Request: When importing commerce products, it would be great if there was a field to set 'active/inactive' status on variants.

### Additional info

- Plugin version: FeedMe 3.0.0-beta.17, FeedMe Pro 3.0.4, Commerce 2.0.0-beta.7
- Craft version: Craft CMS 3.0.19

**Comment by engram-design** [comment]
Added in the latest craft-3 branch, and will be in the next beta shortly.
