### ISSUE TITLE
CSV's with newlines in the headings silently fail to import data

### ISSUE THREAD

**Issue by TobyJGray** [verbb/feed-me#376]
### Description
When importing data from a csv into entries if the csv's heading row has a newline character (LF) in a cell any mapping for that column's data will not save and importing that column's data will fail

(Newlines in actual cells with data do not cause issues)

The column 'New Line' will fail to map to a field in feedme and as such 11 isn't saved into the generated entry
![image](https://user-images.githubusercontent.com/18116646/44083057-e6fa6d86-9faa-11e8-8bee-599c36218d95.png)

### Steps to reproduce

1. Create a csv with some dummy data and add a newline to one of the heading cells 
2. Set up feed as normal, when you try to map fields and save it will silently revert to dont import for the field with a new line
![image](https://user-images.githubusercontent.com/18116646/44083315-8beea03c-9fab-11e8-8414-64ab462fda9c.png)
3. Either run the feed or use the debug option and the data in the column with a newline and you will see the data is not imported

![image](https://user-images.githubusercontent.com/18116646/44083632-77ea7844-9fac-11e8-96df-aee6f9c5facb.png)

![image](https://user-images.githubusercontent.com/18116646/44083672-941d7480-9fac-11e8-9e49-71d535ff0ca1.png)

### Additional info

- Plugin version: 3.0.0-beta.17
- Craft version: Craft Solo 3.0.16.1

**Comment by engram-design** [comment]
Fixed in the latest craft-3 and will be rolled into the next beta release.
