### ISSUE TITLE
Updating assets not matching existing assets by filename

### ISSUE THREAD

**Issue by oadslug** [verbb/feed-me#382]
### Description

I'm attempting to update existing assets to add additional custom field data (i.e. title, description, etc—that could not be imported when importing entries, products, variants, etc.). But when I run the import I get an error 'Unable to match an existing element.' The current assets are in subfolders, but I wouldn't think that would matter.

In addition to importing title, description — the plan was to use this to change the filename from the ugly hashed name to a more human-readable name. Step one, update a custom asset field with the hashed filename. Step two, match on the new hashed filename field, and update filename to human-readable name. Don't know if that will work — but will give it a shot.

This is sort of a workaround for this [feature request](https://github.com/verbb/feed-me/issues/157).

### Steps to reproduce

1. Set Feed URL, Element Type: Assets, Asset Source, etc.
2. Set Import Strategy to 'Update existing elements' only
3. Map 'filename' to CSV 'filename' (and uncheck 'Create asset from URL')
4. Map 'folder' to 'do not import'
5. Map content fields (description, etc)
6. Set unique identifier for existing elements to 'Filename'.

### Additional info

- Plugin version: Craft CMS 3.0.21
- Craft version: 3.0.0-beta.21

**Comment by engram-design** [comment]
Actually, well picked up, subfolders weren't included in search against existing assets, they are now.

And your second part is probably the best way to go. The tricky part with matching assets are finding unique data, but that FR is certainly on the cards.

Closing here, but follow along that FR.
