### ISSUE TITLE
Resource files renamed can cause errors on some servers.

### ISSUE THREAD

**Issue by lettie16** [verbb/feed-me#384]
### Description
Recently updated from v1 to v2. Worked fine on my local server but once pushed to staging I had an issue with the CP in that it could not find the feedme.js and feedme.css files as the calls to these files have now been updated to FeedMe.js and FeedMe.css. On a case sensitive set up these files fail to be found.

### Steps to reproduce

1.
2.

### Additional info
Would suggest renaming the include calls back to lower case to avoid this.

- Plugin version: 2.0.13
- Craft version: 2.6.3017

**Comment by engram-design** [comment]
Updated in [2.0.14](https://github.com/verbb/feed-me/releases/tag/2.0.14) release.
