### ISSUE TITLE
Enabled tabs error in release 2.0.13

### ISSUE THREAD

**Issue by Nathanw** [verbb/feed-me#386]
### Description
Version 2.0.13 is broken due to it missing PR #380, the plugin can not be accessed at all in the backend due to "Invalid argument supplied for foreach()". Could you please create a new release containing this fix?

**Comment by davidhellmann** [comment]
Same problem here

**Comment by bymayo** [comment]
I'm also getting this issue

**Comment by DougThwaites** [comment]
Ditto

**Comment by bymayo** [comment]
As a quick fix, I amended the `settings` column in `craft_plugins` table for feed me, to have the content:

`{"pluginNameOverride":"","cache":"60","enabledTabs":"*","edition":"0"}`

It looks like it needed the enabled tabs settings. I imagine this needs a migration to add this in to the settings.

**Comment by engram-design** [comment]
Fixed in [2.0.14](https://github.com/verbb/feed-me/releases/tag/2.0.14) release.
