### ISSUE TITLE
Field mapped to Craft postDate field is +1 hour in some cases

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/feed-me#388]
### Description

This continues on from the saga originally explained here in #380. It turns out the original fix created by @kevinsmith, is solid. By placing craft()->timezone on that line does indeed mess around with other date/time fields, my PR commit should be reverted, it will cause a regression and likely break other people's feeds. My apologies. 

However, this still creates a problem for my bizarre issue when mapping to Craft's postDate field.

To clarify, you can find an XML data sample which is affected by the issue in my feed below. Essentially the `created_date` field is mapped to Craft's `entry.postDate` field.

```
<Item>
            <team>BJA001</team>
            <parent_coursecode>C024214</parent_coursecode>
            <course_code>Q024215</course_code>
            <calocc_code>18/19</calocc_code>
            <course_title>CC-EL-Sewing for Beginners-MMW-Aug-Wed</course_title>
            <aim_code>Z0008530</aim_code>
            <qual_aim_title>Non regulated Adult skills formula funded provision, Entry Level, Crafts, Creative Arts and Design, 7 to 12 hrs, PW C</qual_aim_title>
            <level>E</level>
            <course_status>INACTIVE</course_status>
            <marketing_title null="1" />
            <unit_category>Further Education</unit_category>
            <partner null="1" />
            <study_location_code>MMW</study_location_code>
            <study_location_name>Maid Marian Way Site</study_location_name>
            <website>Y</website>
            <can_apply>N</can_apply>
            <ID>67024</ID>
            <course_description_long>CC-EL-Sewing Made Easy-MMW-Aug-Wed</course_description_long>
            <course_description_full null="1" />
            <course_description_long2>CC-EL-Sewing for Beginners-MMW-Aug-Wed</course_description_long2>
            <owning_organisation>BJA001</owning_organisation>
            <moa_code>PTD</moa_code>
            <course_category>FE</course_category>
            <course_status1>INACTIVE</course_status1>
            <start_date>01-08-2018 00:00:00</start_date>
            <end_date>08-08-2018 00:00:00</end_date>
            <start_time>01-01-1900 09:30:00</start_time>
            <end_time>01-01-1900 16:00:00</end_time>
            <FES_DAY_OF_WEEK>WED</FES_DAY_OF_WEEK>
            <location_code>MMW</location_code>
            <location_description_short>Maid Marian </location_description_short>
            <location_description_long>Maid Marian Way Site</location_description_long>
            <course_level>E</course_level>
            <created_date>14-06-2018 09:45:41</created_date>
            <updated_date>01-08-2018 11:30:21</updated_date>
            <advance_fee>0.00</advance_fee>
            <app_fee>0.00</app_fee>
            <exam>0.00</exam>
            <fc_fee>0.00</fc_fee>
            <fe_fee>39.00</fe_fee>
            <he_fee>0.00</he_fee>
            <mat_fee>0.00</mat_fee>
            <lars_matrix_rate>50</lars_matrix_rate>
        </Item>
```

### Steps to reproduce

Importing this data sample via XML, causes the postDate value in Craft to be 14/06/2018 10:45:41. All timezone settings within Craft are configured for `Europe/London`, I've also confirmed our PHP config is running under `Europe/London` as well. However, regardless this record always imports as +1 on the time, but it makes no sense because other records are absolutely fine. So I frankly have no idea what is different with this sample compared to another.

What I do know is having `craft()->timezone` called on the `created_date` parsedDate did seem to fix the issue and not cause problems with other `postDate` values.

Either something configuration wise in our Craft install is causing this, some edge case in FeedMe or maybe even a Craft 2 bug possibly?

Any advice on this would be appreciated! 

Thoroughly confused,

James

### Additional info

- Plugin version: 2.0.13
- Craft version: 2.7.2

**Comment by engram-design** [comment]
Happy with what you've put together, and is in the [2.0.14](https://github.com/verbb/feed-me/releases/tag/2.0.14) release.
