### ISSUE TITLE
Cron Job Import not triggering EVENT_AFTER_SAVE?

### ISSUE THREAD

**Issue by whoisjuan** [verbb/feed-me#389]
### Description
I have a couple of things in my Craft, that depend on listening for this event. One is a preparse field and the other one is a notification system. Both of them are triggered correctly when you create an entry manually.
This also used to work well with my FeedMe imports, but something happened in the last two weeks and they stopped working.
FeedMe does the import correctly, but it seems that the EVENT_AFTER_SAVE is not getting triggered when FeedMe creates the entry.

Seems like this happened after updating to Craft 3.0.22, but I'm not entirely sure this has to do with that. 
Any clue on what might be going on?

### Steps to reproduce

1. Import an Entry with FeedMe (Only tested with Cron triggered imports)
2. Listen for EVENT_AFTER_SAVE --> Doesn't fire or something prevents it from being listened.

### Additional info

- Plugin version: 3.0.0-beta.21
- Craft version: 3.0.22

**Comment by engram-design** [comment]
I can confirm the following events work.
```
Event::on(\craft\elements\Entry::class, \craft\base\Element::EVENT_AFTER_SAVE, function(\craft\events\ModelEvent $event) {
    file_put_contents('testing.txt', 'data');
});
```

```
Event::on(\craft\services\Elements::class, \craft\services\Elements::EVENT_AFTER_SAVE_ELEMENT, function(\craft\events\ElementEvent $event) {
    file_put_contents('testing.txt', 'data');
});
```
These will trigger via the debug action, or when triggering the direct URL via your browser, command line or cron. I has created a module with these events to test this.

Maybe something else might be going on in your system? You should be able to test it easier triggering the debug action for the feed, and outputting content?

Closing for now, but feel free to respond with code you're using if you can reproduce it.

**Comment by whoisjuan** [comment]
Hey Josh. Still totally lost with this issue. I have been trying to figure out something from the logs but no success.

The plugin that I'm using is Preparse Field https://github.com/aelvan/Preparse-Field-Craft. After creating an entry and saving it, the preparse field will get data from other field and do a small conversion. This always works with a manual save but fails when importing with FeedMe. Again, this used to work, but then it stopped working. I don't know when exactly.

Here is the Preparse plugin file with the event handlers: **https://github.com/aelvan/Preparse-Field-Craft/blob/craft3/src/PreparseField.php**

Everything there seems right based on the information you provided before. In theory, if FeedMe is firing those events, then this event handler should listen for those events, but that only happens when I save manually.

Any idea on what might be going on?

**Comment by whoisjuan** [comment]
Fixed it finally. Configuration error on my side.
