### ISSUE TITLE
Title-field is not updating title on file on remote import

### ISSUE THREAD

**Issue by espensgr** [verbb/feed-me#391]
### Description
I have setup a feed with assets, here is an example of two pictures:

````
    {
        "ImageId": 8056,
        "PublicId": "6a5cfff0-d596-4bee-b7aa-25a3a85146e7",
        "ImageUrl": "https://lindbak.papirfly.no/readimage.aspx?custom=max:1200x1200&pubid=6a5cfff0-d596-4bee-b7aa-25a3a85146e7.jpg",
        "Title": "RBM NOOR 6060 rose",
        "FileName": "NOOR_6060_rose[Newspaper].jpg",
        "ProductId": 674,
        "ProductExternalId": "RBM_6060",
        "IsMainImage": true
    },
    {
        "ImageId": 8998,
        "PublicId": "928da909-9e27-4782-b89d-697712302343",
        "ImageUrl": "https://lindbak.papirfly.no/readimage.aspx?custom=max:1200x1200&pubid=928da909-9e27-4782-b89d-697712302343.jpg",
        "Title": "Montana Panton one barstol",
        "FileName": "montana_living2_42.jpg",
        "ProductId": 676,
        "ProductExternalId": "mon_VPTB",
        "IsMainImage": true
    },
````
And here is the current setup for the feed:
![skjermbilde 2018-09-11 16 25 22](https://user-images.githubusercontent.com/3862891/45366553-5bf64200-b5df-11e8-84fc-23241d1013df.png)

The pictures are imported but the Title field gets generated from the filename, not the title field ia have added for the title. Is this a bug or is this intended?

Also, it would be nice to have a import field where the asset-url can be placed, in addition to the filename field. Like in this instance, i have the filenames, title etc. to fill in all the information to the asset.
### Additional info

- Plugin version: 2.0.13
- Craft version: 2.7.2

**Comment by engram-design** [comment]
Fixed in [2.0.14](https://github.com/verbb/feed-me/releases/tag/2.0.14) release.
