### ISSUE TITLE
Integrity Constraint Violations

### ISSUE THREAD

**Issue by benjaminkohl** [verbb/feed-me#392]
### Description

I recently updated Feed Me to 3.0.0-beta.21 and Feed Me Pro to 3.0.4. Import processes that we ran routinely without trouble now fill the Feed Me log and Craft queue log with this error message: "Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous\nThe SQL being executed was:" The query is a big one and the error takes place in Schema.php on line 664.

### Steps to reproduce

1. Run any feed import.

### Additional info

- Plugin version: 3.0.0-beta.21 / 3.0.4
- Craft version: 3.0.24

**Comment by sjcallender** [comment]
Same as https://github.com/verbb/feed-me/issues/387

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.22](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.22).
