### ISSUE TITLE
Mapping multiple entry points from XML

### ISSUE THREAD

**Issue by rhoffmann** [verbb/feed-me#393]
### Description

I have a case where i need to import multiple categories (and different languages) from an XML file. They are grouped under a parent Node and all use the same XML Attribute type (`TLookupItem`). The Problem is, that the Attribute type is only recognized once as a repeatable content, not for each Parent Node. 

In the Dropdown to select the Parent Node from the Feed it shows only *one* option to select the lookup Item: 

`Lookups/TLookupTopicDE/TLookupItem (x32 elements)`. 

(which is probably the last one parsed, seems quite arbitrary?) 

The *other category feeds* are only shown as 

`Lookups/TLookupTopicEN` (x1 elements) 
`Lookups/TLookupSomeOtherCategoryDE` (x1 elements)
`Lookups/TLookupSomeOtherCategoryEN` (x1 elements)

without the TLookupItems children showing up. I would expect to be able to select all repeated child elements in all parent nodes.

One current workaround is to split everything in multiple files, or make the child node names unique per parent node, which is not quite practical.

The Categories are grouped like this:

```
<Lookups>
  <TLookupTopicDE>
      <TLookupItem>...</TLookupItem>
      <TLookupItem>...</TLookupItem>
      ...
  </TLookupTopicDE>

  <TLookupTopicEN>
     <TLookupItem>...</TLookupItem>
     <TLookupItem>...</TLookupItem>
  </TLookupTopicEN>

 <TLookupSomeOtherCategoryDE>
   <TLookupItem>...</TLookupItem>
 </TLookupSomeOtherCategoryDE>

 <TLookupSomeOtherCategoryEN>
   <TLookupItem>...</TLookupItem>
 </TLookupSomeOtherCategoryEN>
</Lookups>

### Additional info

- Plugin version: feed-me: dev-craft-3, feed-me-pro: 3.0.4
- Craft version: 3.0.16.1

**Comment by engram-design** [comment]
Might need some clarification here, as you mention XML attributes, but your example doesn't show that, so just wanted to confirm.

Is this also a category element import, or an entry importing into a categories field?

**Comment by engram-design** [comment]
Closing for now due to inactivity, but please let me know if this need to be re-opened.
