### ISSUE TITLE
"Third-party fieldtype support" removed from `postForFieldType`

### ISSUE THREAD

**Issue by lindseydiloreto** [verbb/feed-me#394]
Craft 2
Updated from **Feed Me 1.4.12** to **2.0.13**

It seems that the "Third-party fieldtype support" in `postForFieldType` hook has disappeared...

https://github.com/verbb/feed-me/blob/1.4.12/feedme/services/FeedMe_FieldsService.php#L507
https://github.com/verbb/feed-me/blob/2.0.13/feedme/services/FeedMe_FieldsService.php#L49-L66

I have a feed that sends a JSON packet as one of its fields. When the field is received, it gets unpacked, and different parts get applied to different things. This feature would be sorely missed if I upgrade.

Let me know if you need any additional information. Thanks! 🙂

**Comment by engram-design** [comment]
Added in [2.0.14](https://github.com/verbb/feed-me/releases/tag/2.0.14) release.

**Comment by lindseydiloreto** [comment]
Brilliant, thanks @engram-design! 🍺
