### ISSUE TITLE
Adjustment to `postForFeedMeFieldType`

### ISSUE THREAD

**Issue by lindseydiloreto** [verbb/feed-me#395]
Related to #394 

In the old version (1.4.12), I had made a minor hack to improve the `postForFieldType` callback.

**ORIG:**
```php
craft()->plugins->call('postForFeedMeFieldType', array(&$fieldData));
```

**HACK:**
```php
craft()->plugins->call('postForFeedMeFieldType', array(&$fieldData, $element));
```

And of course the `postForFeedMeFieldType` function was modified to accommodate the second parameter. This allowed the field data to be applied with respect to other details in the element.

Assuming you re-introduce support for this hook, it would be amazing if you included this minor modification!

**Comment by engram-design** [comment]
Added in [2.0.14](https://github.com/verbb/feed-me/releases/tag/2.0.14) release, although note that the method signature has changed.

```
craft()->plugins->call('postForFeedMeFieldType', array(&$preppedData, $element, $field, $data, $handle));
```

**Comment by lindseydiloreto** [comment]
Excellent! Thanks man, much appreciated!  👍
