### ISSUE TITLE
Super Table Support

### ISSUE THREAD

**Issue by jeffaglenn** [verbb/feed-me#398]
Is there Super Table support for Feed Me? I've searched but can't find anything and feel like I'm just missing it?

**Comment by engram-design** [comment]
Not yet for Craft 3, but its the next thing on our list. Look for it in the next few weeks.

**Comment by engram-design** [comment]
Added in Feed Me [3.0.0-beta.23](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.23) for Craft 3.
