### ISSUE TITLE
Asset import issue related to folders

### ISSUE THREAD

**Issue by joshuabaker** [verbb/feed-me#399]
### Description

Exceptions when importing assets.

When leaving folder blank...

```
Argument 1 passed to craft\services\Assets::getFolderById() must be of the type integer, null given, called in
```

When providing a folder in the feed...

```
Trying to get property of non-object - Asset.php:153
```

### Steps to reproduce

Set up an asset feed and set folder to any combination of configuration.

### Additional info

- Plugin version: 3.0.0-beta.21
- Craft version: 3.0.25

**Comment by engram-design** [comment]
Are you able to send through a support request through the plugin? I just need to know a bit more about your feed setup, and asset volumes, and folder setup selected.

**Comment by engram-design** [comment]
Closing for now due to inactivity, but please let me know if this need to be re-opened.
