### ISSUE TITLE
Empty array imports to Table fields cause errors

### ISSUE THREAD

**Issue by joshuabaker** [verbb/feed-me#402]
### Description

Importing an empty JSON array into a Table field results in invalid field data, and an error when editing the entry.

### Steps to reproduce

1. Create a feed that imports into a Table field
2. Create a JSON file with an empty array for the Table field
3. Run the feed
4. Go to edit the entry that was created or updated

### Additional info

- Plugin version: 3.0.0-beta.21
- Craft version: 3.0.25

**Comment by joshuabaker** [comment]
I think the same issue as #332.

**Comment by engram-design** [comment]
@joshuabaker Still unable to reproduce this. Can you advise what you're trying to map to a table field with an example?

For instance, I have:
```
"Table": [
  {
    "rowOne": "Some Value",
  },
  {
    "rowOne": "Another Value",
  }
]
```
Which imports correctly, but changing that to:
```
"Table": []
```
Doesn't seem to produce an error?

**Comment by engram-design** [comment]
Although I can produce an error with:

```
"Table": [
  {
    "rowOne": []
  },
  {
    "rowOne": []
  }
]
```
which has been fixed, just wanted to confirm?

**Comment by joshuabaker** [comment]
@engram-design It’s the empty array that we had issues with. Great to hear that’s fixed. Thank you!
