### ISSUE TITLE
Console command to trigger import

### ISSUE THREAD

**Issue by carlcs** [verbb/feed-me#404]
It would be nice to be able to trigger an import via console command.

**Comment by urbantrout** [comment]
You could use curl or wget for that. See https://verbb.io/craft-plugins/feed-me/docs/feature-tour/trigger-import-via-cron

**Comment by engram-design** [comment]
Added in [3.1.6](https://github.com/verbb/feed-me/releases/tag/3.1.6). See https://verbb.io/craft-plugins/feed-me/docs/feature-tour/trigger-import-via-cron#console-command
