### ISSUE TITLE
Twig Error when trying to create field with no sections set up

### ISSUE THREAD

**Issue by fantasticmachine** [verbb/feed-me#408]
### Description
When trying to create a new field, a Twig Exception is thrown if there are no Sections already set up.
In my case I was looking to import Commerce product data.

The workaround is to create a Section. No need to populate it with fields or entries. 

### Steps to reproduce

1. have a Craft Installation without any Sections set up.
2. attempt to create a new Feedme Feed

### Additional info

- Plugin version: 3.0.0.beta2 / Pro 3.0.4 (trial mode)
- Craft version: 3.0.27.1

**Comment by engram-design** [comment]
This should be fixed in [3.0.0-beta.23](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.23).
