### ISSUE TITLE
Categories are duplicated rather than re-used

### ISSUE THREAD

**Issue by camelskyscraper** [verbb/feed-me#412]
### Description

I have a JSON feed going into Entries that is set to add Categories if they don't exist, but it often duplicates them instead using the Title as the key. I notice that the categories' titles that are duplicated all have a comma in them while the categories that are re-used rather than duplicated do not have commas in the titles. 

I submitted a help request through the plugin and can provide more information but I'm not sure where to start.

### Additional info

- Plugin version: Feed Me 3.0.0-beta.25; Feed Me Pro 3.0.4
- Craft version: Craft Solo 3.0.28

**Comment by camelskyscraper** [comment]
More detail, showing another issue that may or may not be related to the duplicating of categories.
Here is what the JSON looks like:
```javascript
"resource_authors":["Bracken, Hillary","Shochet, Tara","Winikoff, Beverly"]
```

The FeedMe debug shows this for the same item:
```javascript
[authors] => Array
        (
            [0] => 
            [1] => 14303
            [2] => 
        )
```

And then the entry itself only shows one author (the middle one).

What else can I provide to help troubleshoot this?

**Comment by engram-design** [comment]
Should be fixed in [3.0.0-beta.26](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.26).

**Comment by camelskyscraper** [comment]
Great, I look forward to checking this out. How long does it typically take for updates to show up as available in the Craft admin panel?

**Comment by camelskyscraper** [comment]
Eventually it came up, and the import worked as expected, thanks!
