### ISSUE TITLE
Calling unknown method: craft\console\Request::getSegment() - Component.php: 300

### ISSUE THREAD

**Issue by slebbo** [verbb/feed-me#413]
### Description
I keep getting this error; 
`Calling unknown method: craft\console\Request::getSegment() - Component.php: 300`

Example from the logs:

[info] 
```Feed from YouTube: Match existing element with data {"title":"Gucci Spring Summer 2016 Campaign Film"}. ```
[info] 
```Feed from YouTube: Data ready to import {"title":"Gucci Spring Summer 2016 Campaign Film","youtubeId":"l9b5jym0ig8"}. | 10/30/2018 8:29 AM```
[error] 
```Feed from YouTube: Calling unknown method: craft\console\Request::getSegment() - Component.php: 300.```

### Steps to reproduce

1. XML-feed from youtube
2. Mapping a title-field -> title (craft title field)
3. Mapping a youtube-id-field -> youtubeId (craft plain text field)

### Additional info

- Plugin version: 3.0.0-beta.25
- Craft version: 3.0.28

**Comment by whoisjuan** [comment]
Getting this error as well in some instances as well (in addition to the one reported here: https://github.com/verbb/feed-me/issues/414)

**Comment by engram-design** [comment]
How are you triggering your feed by the way?

**Comment by whoisjuan** [comment]
> How are you triggering your feed by the way?

I don't about OP, but mine is triggered by calling the feed Cron URL.

**Comment by engram-design** [comment]
Should be fixed in [3.0.0-beta.26](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.26).

**Comment by slebbo** [comment]
Thank you for fixing that so quickly Josh!
