### ISSUE TITLE
Class 'verbb\feedme\fields\FeedMe' not found - Tags.php: 111

### ISSUE THREAD

**Issue by whoisjuan** [verbb/feed-me#414]
### Description
My imports are failing and outputting this error after updating to 3.00-beta.25
Class 'verbb\feedme\fields\FeedMe' not found - Tags.php: 111

Not exactly sure what's happening. This is what the new more detailed logs are showing after I attempt to import.

### Steps to reproduce

1. Run my usual workflow to import using a JSON file.
2. Error: Class 'verbb\feedme\fields\FeedMe' not found - Tags.php: 111

### Additional info

- Plugin version: 3.00-beta.25
- Craft version: 3.0.29

**Comment by whoisjuan** [comment]
I downgraded via composer using `composer require verbb/feed-me:3.0.0-beta.24` and the imports that I was attempting before with the new version ran without problems. So at this point, I believe this a beta.25 specific issue.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.26](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.26).
