### ISSUE TITLE
"Integrity constraint violation: 1062 Duplicate entry on new asset" when asset doesn't already exist

### ISSUE THREAD

**Issue by camelskyscraper** [verbb/feed-me#416]
### Description
I'm importing to Assets and removed all assets from the target folder through the Craft admin.
When I try to re-run the feed I get the PDOException
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Sn.UvM_PPH_P.8a.jpg-1' for key 'assets_filename_folderId_unq_idx'
```
This happens on the very first item.
The item's filepath does not have the "-1" on it so it's like it is creating the asset then trying to recreate it and appending the "-1".
The asset folder has been cleared (deleting the assets through Craft) but maybe there is some sort of memory of it somewhere in Craft anyway?

### Additional info

- Plugin version:  3.0.0-beta.26, Pro 3.0.4
- Craft version: Craft Solo 3.0.29

**Comment by engram-design** [comment]
It might be worth trying to clear your caches to see if that helps.

Otherwise, would you be able to send through a Help request from the Help tab in Feed Me? Just need a bit more information about your setup.

**Comment by camelskyscraper** [comment]
Just tried clearing all the caches and re-trying, to no avail.
Sent in a request through the Help tab.
Thank you for your attention on this!

**Comment by engram-design** [comment]
This should be fixed in https://github.com/verbb/feed-me/releases/tag/3.0.0.
