### ISSUE TITLE
Uploading users suspended every account

### ISSUE THREAD

**Issue by Coysh** [verbb/feed-me#422]
### Description
When using a .csv of members to import, Feed Me suspended all accounts in the database - including super admin.

### Additional info

- Plugin version: 3.0.0-beta.29 AND 2.5.0
- Craft version: Craft Pro 3.0.31
--

**Comment by engram-design** [comment]
Are you able to submit a Help request through the plugin? I'll need more information about your mapping and import strategy.

**Comment by Coysh** [comment]
Done.

Digital lead | Evangelical Alliance
________________________________

**Comment by Coysh** [comment]
The issue seems to be the "Disable missing elements" option. This seems to work differently before, as it now suspends users not listed in the .CSV, whereas before it did not alter users.

Tim

**Comment by engram-design** [comment]
That's correct behaviour as someone requested this change, which was changed in [3.0.0-beta.27](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.27). There's no 'disabled' state of users, the only equivalent in suspended.

However, I can see how this isn't that clear. I'll be sure to add clarification to that field when importing users is selected.

**Comment by Coysh** [comment]
Okay. Thanks for the update – it does make sense I guess!
Some clarification for others might make sense.

**Comment by engram-design** [comment]
Improved in [3.0.0](https://github.com/verbb/feed-me/releases/tag/3.0.0).
