### ISSUE TITLE
Option to add sleep(1) to each item processing

### ISSUE THREAD

**Issue by carlcs** [verbb/feed-me#424]
I have items in my feed ordered manually and want to maintain that order after importing. Now Feed Me is just too fast so that many element are getting the exact same Creating Date (and default Post Date).

It would be nice if there was an option in the feed settings that’d allow each item processing to take at least one second, so exact same dates won’t be possible any more.

**Comment by engram-design** [comment]
Ha, I suppose that's a good problem to have (going too fast)!

I've added this function in [3.0.0](https://github.com/verbb/feed-me/releases/tag/3.0.0), but you could also achieve this with some events [stepAfterElementSave](https://verbb.io/craft-plugins/feed-me/docs/developers/events#the-stepAfterElementSave-event).

**Comment by carlcs** [comment]
Whoo 3.0 is out! And thanks for adding the option.
