### ISSUE TITLE
Invalid XML: xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by studiosyntax** [verbb/feed-me#428]
### Description
When setting up a new feed I get the following error;

`Invalid XML: xmlParseEntityRef: no name : Line #7.`

I'm assuming it's because of bad XML content formatting, but unfortunately I don't have control over the XML output. There don't seem to be crazy characters, but `CDATA` markup is missing.

Is there a way I can get this XML to pass somehow?

### Steps to reproduce
1. Set up a new XML feed
2. Click Save and continue

### XML output details
```
<?xml version="1.0" encoding="UTF-8" ?>
<rating><score>9.3</score><scoremax>10</scoremax><noReviews>785</noReviews><detailslink>https://www.feedbackcompany.com/nl-nl/reviews/clientname/</detailslink><reviewDetails></reviewDetails></rating>
```

### Additional info

- Plugin version: 3.0.0-beta.30
- Craft version: 3.0.31

I can e-mail the link to the XML, would rather not post it public since it's a client thing.

**Comment by engram-design** [comment]
That XML snippet looks fine, but it depends on what the rest of your feed is show - ie, what's on line 7?

Unfortunately though, there's no effective way Feed Me can parse the content of your feed if its simply not formatted correctly, or to a standard.

There's some hooks you could make use of to first wrap the content's of your feed with CDATA? [afterFetchFeed](https://verbb.io/craft-plugins/feed-me/docs/developers/events#the-afterFetchFeed-event)
