### ISSUE TITLE
Recommended way to modify feed data before import

### ISSUE THREAD

**Issue by elivz** [verbb/feed-me#430]
What is the canonical way to modify the data from the external feed before running the import process? In my case, I want to filter out some elements from the JSON feed (expired entries, etc.) before running the import. I would guess that the `afterFetchFeed` event would be the place to do that, but if I am reading things right I can't actually modify the feed data there, just look at it. Am I wrong about that? Is there another hook that I could use instead? Thanks!

**Comment by engram-design** [comment]
Yep, but I've just realised the `afterFetchFeed` is probably firing a bit too early, as that contains the raw JSON/XML/etc response. You'll likely want to manipulate it after Feed Me has parsed it into an array.

Check out [afterParseFeed](https://verbb.io/craft-plugins/feed-me/docs/developers/events#the-afterParseFeed-event) which I've just added in [3.0.0](https://github.com/verbb/feed-me/releases/tag/3.0.0).

```
Event::on(DataTypes::class, DataTypes::EVENT_AFTER_PARSE_FEED, function(FeedDataEvent $event) {
    if ($event->response['success']) {
        $event->response['data'][0]['title'] = 'OVERRIDE';
    }
});
```
