### ISSUE TITLE
Issue with getLicenseKey function in FeedMe_LicenseService.php

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/feed-me#432]
### Description

I noticed that the license key is not be set if done via config. It looks like it's because the wrong name is being used for the `craft()->config->get`, it should be all lowercase as per the docs here: https://docs.craftcms.com/v2/plugins/plugin-settings.html#config-file

Offending line:

https://github.com/verbb/feed-me/blob/craft-2/feedme/services/FeedMe_LicenseService.php#L71

**Comment by engram-design** [comment]
Mentioned in [#431](https://github.com/verbb/feed-me/issues/431), but this isn't a typo. Its looking for `licenseKey` in the `config/feed-me.php` config file, so nothing to do with Craft.

**Comment by jamesmacwhite** [comment]
Hi. @engram-design. It's not the license key value that's wrong. It's the fact it uses feedMe instead of feedme for the config name. According to the docs, when use config get the handle of the plugin name should be lowercase. Sorry for the confusion. I tested it and currently that config var will return null all the time, unless changed.

**Comment by engram-design** [comment]
Well, dunno how or why but it worked when I initially did this - who knows!

And yes, `feedme.php` - I'm 100% in Craft 3 land these days where its the other.

**Comment by jamesmacwhite** [comment]
@engram-design No worries. Just clarifying to make sure I've understood the config var. I believe the plugin handle change is correct for Craft 2 plugins, based on the docs.

**Comment by engram-design** [comment]
Fixed in [2.0.17](https://github.com/verbb/feed-me/releases/tag/2.0.17)
