### ISSUE TITLE
Feed Me v3.0.2 Class 'verbb\feedme\elements\BaseElement' not found - CommerceProduct.php: 118

### ISSUE THREAD

**Issue by xhuang9** [verbb/feed-me#441]
### Description

Bugs for latest release at 3.0.2
In feed-me/src/elements/CommerceProduct.php line 118
    $this->element->setScenario(BaseElement::SCENARIO_ESSENTIALS);

BaseElement has no library to refer to, I can't process any feed.

### Steps to reproduce

1. Process any feed

### Additional info

- Plugin version: 3.0.2
- Craft version: 3.0.35

**Comment by engram-design** [comment]
Sorry about that, fixed in [3.0.2.1](https://github.com/verbb/feed-me/releases/tag/3.0.2.1)

**Comment by xhuang9** [comment]
That was quick
