### ISSUE TITLE
Importing Decimal Number into Numbers Field

### ISSUE THREAD

**Issue by exophunk** [verbb/feed-me#443]
### Description

I have a CSV containing products with prices. Prices are decimal numbers in this format: `80.61`. I am importing this into a Craft Numbers field. But the decimal point gets ignored and the imported field ends up as `8061.00`.

Is there a setting (maybe US/EN Decimal delimeter) or something I need to consider when importing Numbers?

### Steps to reproduce

1. Import CSV Feed with decimal numbers
```
Titel,Produktekategorie,Preis ,Beschreibung
ars viva 09/10,Tragtaschen,80.61,"Lorem ipsum dolor si sit amet."
```
2. Try to import it into a Numbers field.

### Additional info

- Plugin version: Feed Me 3.0.2.1
- Craft version: Craft CMS 3.1.0-beta.5.1

**Comment by jdsimcoe** [comment]
@exophunk this appears to be related to: https://github.com/verbb/feed-me/issues/435.

**Comment by engram-design** [comment]
Can't seem to replicate this I'm afraid. I imagine your number field has decimals setup?

What locale are you importing into (or what is the one for your primary site)?

**Comment by engram-design** [comment]
Ah, good to know its importing into the German locale, I'd say that's definitely a factor. I also thought that using a comma was correct for the German language, is that not correct?

The reason I ask is that this comes down to (at the moment) the current users' language setting. Is set to English, it imports "80.61" as "80.61". If set to Deutsch it will import "80.61" as "8061". This is more a Craft localisation functionality (`Localization::normalizeNumber()`), which according to that function the German decimal symbol is "," (comma).

I believe there's a config setting you can set for the actual locale, but it might be worth us double checking this is correct.

**Comment by exophunk** [comment]
Ah! Indeed, for german, a comma would be correct.

I found out that in Switzland (where I live) it is different again and a decimal point is correct. We usually use `de`instead of `de_ch` as locale for simplicity. i didn't know there is a difference, as we speak german too. Weird standards :)

Anyway it then is not an issue of feed-me, but actually correct.
