### ISSUE TITLE
Timestamps are not imported correctly

### ISSUE THREAD

**Issue by exophunk** [verbb/feed-me#445]
### Description
When importing timestamps that are not exactly 10 digits, the date fields are not getting imported correctly and the feedme log shows an error.

The issue is this line:
https://github.com/verbb/feed-me/blob/craft-3/src/helpers/DateHelper.php#L46

There are also timestamps that have less than 10 digits (older dates). For example:

883612800: (1 January 1998) --> 9 digits

You can check it here: https://www.epochconverter.com/

### Steps to reproduce

1. Import timestamp integer into DateTime field
2. Use timestamp with less than 10 digits (something before year 2000)
3. Importer throws error, as it doesn't process value as timestamp and later tries to parse DateTime string, which fails

### Additional info

- Plugin version: 3.0.2.1
- Craft version: 3.0.36

**Comment by engram-design** [comment]
Yeah, I knew this wasn't a great solution even at the time. I'll likely refactor this to specifically state whether the provided data is in milliseconds or seconds.

**Comment by engram-design** [comment]
This has been improved in [3.1.0](https://github.com/verbb/feed-me/releases/tag/3.1.0) by including a dropdown to select either seconds or milliseconds for date inputs.
