### ISSUE TITLE
Unknown method during import

### ISSUE THREAD

**Issue by ul8** [verbb/feed-me#446]
### Description

Getting this error in the log during import:

Calling unknown method: craft\console\Request::getBodyParam() - Component.php: 300

Thanks for your help!

### Steps to reproduce

1. Import a CSV file using:
- import into entries
- update existing elements
- match unique identifier against numeric field
- just one other numeric field mapped to write into

(this is the specific import I noticed this in, might apply to other parameters too)

### Additional info

- Plugin version: 3.0.2.1
- Craft version: 3.0.37

**Comment by engram-design** [comment]
How are you triggering this feed by the way? Seems to be through a console command or something similar?

**Comment by ul8** [comment]
Sorry - this turned out to be a side effect of an issue in another plugin (craft-scout), runs fine with that plugin disabled.

**Comment by ul8** [comment]
I'm triggering this feed via the control panel, not via the console. 
```
error | Import Billomat Kunden ID: Starting processing of node #123.Show detail | 25.1.2019 13:20
-- | -- | --
info | ↳ Import Billomat Kunden ID: Match existing element with data {"legacyId":"6542"}. | 25.1.2019 13:20
info | ↳ Import Billomat Kunden ID: Existing element #5842 found. | 25.1.2019 13:20
info | ↳ Import Billomat Kunden ID: Data to update for billomatId: "2229899". | 25.1.2019 13:20
info | ↳ Import Billomat Kunden ID: Data ready to import {"legacyId":"6542","billomatId":"2229899"}. | 25.1.2019 13:20
error | ↳ Import Billomat Kunden ID: Calling unknown method: craft\console\Request::getBodyParam() - Component.php: 300. | 25.1.2019 13:20
```

Just tried the debug action, this outputs a long list like this:
```
billomatId - existing
billomatId - new
2229776
Array
(
    [legacyId] => 2
    [billomatId] => 2229776
)
```
This repeats for each entry - couldn't spot any irregularities.

**Comment by ul8** [comment]
Mysteriously, it now worked - I just noticed the debug action has managed to import it fine. Is the debug action doing anything differently? I expected it would only log errors.

I just confirmed the normal feed run still does not work. I deleted one element's imported data and imported again. The same error comes up. (If I don't delete it before the import there is no error as the plugin does not attempt to overwrite the data).

**Comment by engram-design** [comment]
Thanks for this, the debug action will import things - it'll just be a little slower with a bit more output. It does seem to be an issue of when its called via the Queue system, which the debug action doesn't do.

I wonder if you have any other plugins installed of note that might throw this error? Maybe if you can shoot through your composer.json file?

**Comment by ul8** [comment]
I'll give it a go with various plugins disabled and see if anything changes when I get the time. Feel free to close the issue in the meantime, as this is probably not related to feed-me at all..Thanks!!

**Comment by engram-design** [comment]
Sure thing, I'll re-open if this continues to be an issue!
