### ISSUE TITLE
Previous filled CSV fields don't get overwritten

### ISSUE THREAD

**Issue by internetztube** [verbb/feed-me#448]
### Steps to reproduce

1. Import CSV with values filled in
2. Remove values
3. Import
4. Old values are still in the craft fields

### Additional info

- Plugin version: 3.0.2.1
- Craft version: 3.0.37

--

**Comment by engram-design** [comment]
Should be fixed in [3.1.0](https://github.com/verbb/feed-me/releases/tag/3.1.0).
