### ISSUE TITLE
Categories being created on wrong site

### ISSUE THREAD

**Issue by Djive** [verbb/feed-me#452]
We are importing entries per site on our multisite setup.
First we import all entries to site1, then to site2, and so on.
Some sites don't have the same categories so we opted for option "Create categories if they do not exist".
However, no matter on what site we import entries, those categories are always created only on main site.
This also results in the recreation of the categories for every entry because the import cannot find newly created category on the site we are importing to.

- Plugin version: Feed Me 3.0.2.1 
- Craft version: Craft Pro 3.0.37

**Comment by engram-design** [comment]
Fixed in [3.1.1](https://github.com/verbb/feed-me/releases/tag/3.1.1).

**Comment by Djive** [comment]
Craft Pro 3.1.7

Tried to update Feed me plugin, but got an error:

Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: remove nesbot/carbon 1.36.2
- Conclusion: don't install nesbot/carbon 2.11.0
- Conclusion: don't install nesbot/carbon 1.36.2
- Installation request for verbb/feed-me 3.1.1 -> satisfiable by verbb/feed-me[3.1.1].
- verbb/comments 1.0.5 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.36.2, 1.36.1, 1.36.0, 1.35.1, 1.35.0, 1.34.2, 1.34.3, 1.34.4, 1.34.1, 1.34.0, 1.33.0, 1.32.0, 1.31.1, 1.31.0, 1.30.0, 1.29.1, 1.29.2, 1.29.0, 1.28.0, 1.27.0, 1.26.4, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.25.0, 1.24.2, 1.24.0, 1.24.1, 1.23.0, 1.22.0, 1.22.1].
- verbb/comments 1.0.5 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.36.2, 1.36.1, 1.36.0, 1.35.1, 1.35.0, 1.34.2, 1.34.3, 1.34.4, 1.34.1, 1.34.0, 1.33.0, 1.32.0, 1.31.1, 1.31.0, 1.30.0, 1.29.1, 1.29.2, 1.29.0, 1.28.0, 1.27.0, 1.26.4, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.25.0, 1.24.2, 1.24.0, 1.24.1, 1.23.0, 1.22.0, 1.22.1].
- verbb/comments 1.0.5 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.36.2, 1.36.1, 1.36.0, 1.35.1, 1.35.0, 1.34.2, 1.34.3, 1.34.4, 1.34.1, 1.34.0, 1.33.0, 1.32.0, 1.31.1, 1.31.0, 1.30.0, 1.29.1, 1.29.2, 1.29.0, 1.28.0, 1.27.0, 1.26.4, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.25.0, 1.24.2, 1.24.0, 1.24.1, 1.23.0, 1.22.0, 1.22.1].
- Can only install one of: nesbot/carbon[1.36.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.36.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.35.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.35.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.3, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.4, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.33.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.32.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.31.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.31.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.30.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.29.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.29.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.29.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.28.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.27.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.4, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.3, 2.10.0].
- Can only install one of: nesbot/carbon[1.25.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.24.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.24.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.24.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.23.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.22.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.22.1, 2.10.0].
- Can only install one of: nesbot/carbon[2.10.0, 1.36.2].
- verbb/feed-me 3.1.1 requires nesbot/carbon ^2.10 -> satisfiable by nesbot/carbon[2.10.0, 2.10.1, 2.11.0].
- Conclusion: don't install nesbot/carbon 2.10.1
- Installation request for verbb/comments 1.0.5 -> satisfiable by verbb/comments[1.0.5].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

**Comment by john-henry** [comment]
I get the same just with some different plugins

````
Composer output: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: don't install nesbot/carbon 2.11.0
- Installation request for verbb/feed-me 3.1.1 -> satisfiable by verbb/feed-me[3.1.1].
- Conclusion: remove nesbot/carbon 1.36.2
- Installation request for rias/craft-notifications (locked at 1.1.1, required as ^1.1) -> satisfiable by rias/craft-notifications[1.1.1].
- solspace/craft3-freeform 2.5.11 requires nesbot/carbon ^1.22.1 -> satisfiable by nesbot/carbon[1.36.2, 1.36.1, 1.36.0, 1.35.1, 1.35.0, 1.34.2, 1.34.3, 1.34.4, 1.34.1, 1.34.0, 1.33.0, 1.32.0, 1.31.1, 1.31.0, 1.30.0, 1.29.1, 1.29.2, 1.29.0, 1.28.0, 1.27.0, 1.26.4, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.25.0, 1.24.2, 1.24.0, 1.24.1, 1.23.0, 1.22.1].
- solspace/craft3-freeform 2.5.11 requires nesbot/carbon ^1.22.1 -> satisfiable by nesbot/carbon[1.36.2, 1.36.1, 1.36.0, 1.35.1, 1.35.0, 1.34.2, 1.34.3, 1.34.4, 1.34.1, 1.34.0, 1.33.0, 1.32.0, 1.31.1, 1.31.0, 1.30.0, 1.29.1, 1.29.2, 1.29.0, 1.28.0, 1.27.0, 1.26.4, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.25.0, 1.24.2, 1.24.0, 1.24.1, 1.23.0, 1.22.1].
- solspace/craft3-freeform 2.5.11 requires nesbot/carbon ^1.22.1 -> satisfiable by nesbot/carbon[1.36.2, 1.36.1, 1.36.0, 1.35.1, 1.35.0, 1.34.2, 1.34.3, 1.34.4, 1.34.1, 1.34.0, 1.33.0, 1.32.0, 1.31.1, 1.31.0, 1.30.0, 1.29.1, 1.29.2, 1.29.0, 1.28.0, 1.27.0, 1.26.4, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.25.0, 1.24.2, 1.24.0, 1.24.1, 1.23.0, 1.22.1].
- Can only install one of: nesbot/carbon[1.36.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.36.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.36.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.35.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.35.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.3, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.4, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.34.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.33.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.32.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.31.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.31.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.30.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.29.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.29.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.29.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.28.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.27.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.4, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.26.3, 2.10.0].
- Can only install one of: nesbot/carbon[1.25.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.24.2, 2.10.0].
- Can only install one of: nesbot/carbon[1.24.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.24.1, 2.10.0].
- Can only install one of: nesbot/carbon[1.23.0, 2.10.0].
- Can only install one of: nesbot/carbon[1.22.1, 2.10.0].
- Can only install one of: nesbot/carbon[2.10.0, 1.36.2].
- verbb/feed-me 3.1.1 requires nesbot/carbon ^2.10 -> satisfiable by nesbot/carbon[2.10.0, 2.10.1, 2.11.0].
- Conclusion: don't install nesbot/carbon 2.10.1
- Installation request for solspace/craft3-freeform 2.5.11 -> satisfiable by solspace/craft3-freeform[2.5.11].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

````

**Comment by engram-design** [comment]
Should be sorted in [3.1.2](https://github.com/verbb/feed-me/releases/tag/3.1.2)
