### ISSUE TITLE
Pagination not working as expected

### ISSUE THREAD

**Issue by billymedia** [verbb/feed-me#455]
### Description
I have a feed, it contains a pagination url which i have tested and returns entries. Yet, the feed gets to the end of the first run and stops. I assume it would continue with the pagination url. Is that correct?

### Steps to reproduce

1. Define pagination url and select in feed settings
2. Run feed

### Additional info

- Plugin version: 3.1.0
- Craft version: 3.1.5
- PHP 7.1

**Comment by billymedia** [comment]
I installed the "queue manager" plugin to view the job, and noticed that despite saving the pagination url in the feed me settings, the job seems to not pick this up.
` "paginationNode": "pagination_url",` (this is correct)
Where as in the same job:
` "paginationUrl": null`

**Comment by billymedia** [comment]
> This maybe related, but the feedme.log file contains lots of this error:
> 
> `{"date":"2019-01-30 14:23:31","type":"error","message":"Members - Active Employers: `Undefined offset: 1\nFailed to prepare SQL: SELECT `elements`.`id`\nFROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`\nFROM `craft_elements` `elements`\nINNER JOIN `craft_categories` `categories` ON `categories`.`id` = `elements`.`id`\nINNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`\nINNER JOIN `craft_content` `content` ON `content`.`elementId` = `elements`.`id`\nINNER JOIN `craft_structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (`structureelements`.`structureId`=:qp0)\nWHERE (`categories`.`groupId`=:qp1) AND (`elements_sites`.`siteId`=:qp2) AND (`title` = :qp3) AND (`content`.`siteId`=:qp4) AND (`elements`.`archived`=:qp5) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=:qp6)\nORDER BY `structureelements`.`lft`, `elements`.`dateCreated` DESC) `subquery`\nINNER JOIN `craft_categories` `categories` ON `categories`.`id` = `subquery`.`elementsId`\nINNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`\nINNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`\nINNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`\nINNER JOIN `craft_structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId`=:qp7)\nORDER BY `structureelements`.`lft`, `elements`.`dateCreated` DESC - Command.php: 264`.","key":"SI9ikns2KBSsDsSZKRyR"} `
> 
> This all worked fine recently, i now need to run the final import and its stopped working. The only difference between then and now is that i updated to craft 3.1.

It seems that this occurs on random records, i have compared one that worked to one that failed and i cannot see any difference at all.

**Comment by engram-design** [comment]
Would you be able to send through a support request through the Help widget for Feed Me? Its all working on my end, so it might be something to do with your feed setup, or perhaps something else...

**Comment by billymedia** [comment]
> Would you be able to send through a support request through the Help widget for Feed Me? Its all working on my end, so it might be something to do with your feed setup, or perhaps something else...

Ive sent the support request via the plugin, Thanks!

**Comment by billymedia** [comment]
I managed to fix the error message, turned out to be the json and field changes. I also found a workaround for pagination url not working, so this is no longer an issue. Thanks for responding and looking into it.

**Comment by engram-design** [comment]
Glad you got it working!
