### ISSUE TITLE
User.php - Argument 1 passed to craft\services\Assets::getFolderById() must be of the type integer, null given

### ISSUE THREAD

**Issue by john-henry** [verbb/feed-me#459]
### Description

Ok so this error appears when importing users with photos from a remote location.

I thought I had it fixed here with a UID fix for User assets with this patch here which may or may not be correct.

https://github.com/john-henry/feed-me/tree/john-henry-patch-1

But what happens when that patch is in place is that I get lots of duplicate assets created based on original file name. Which in turn leads to ` failed to open stream: File name too long - FlysystemVolume.php: 188.` But I believe this duplication was happening long before the 3.1 update just not as bad

See here for a screenshot http://cloud.johnhenry.ie/e36c5780416c

Im guessing something is happening in that temp folder that is not quite right. 

It also adds this line to the `volumefolders` table which Im guessing isn't right either http://cloud.johnhenry.ie/8cb6216554eb

If you need anything else let me know

### Steps to reproduce

1.Import Users from a JSON feed with remote images for Photos
2.Import Strategy is **Create** and **Update**
3. **_Create asset from URL, if exists_** with either  _Replace existing asset_ or _use existing asset_
4. Tried with S3 and local volumes

### Additional info

- Plugin version: 3.1.2
- Craft version:3.1.7

**Comment by engram-design** [comment]
Should be fixed in [3.1.4](https://github.com/verbb/feed-me/releases/tag/3.1.4)
