### ISSUE TITLE
Error when importing array of categories via JSON

### ISSUE THREAD

**Issue by urbantrout** [verbb/feed-me#460]
### Description

I get an error when importing a JSON with categories as array of strings.

> PDOStatement::bindValue() expects parameter 3 to be integer, string given Failed to prepare SQL: SELECT elements.id FROM (SELECT elements.id AS elementsId, elements_sites.id AS elementsSitesId, content.id AS contentId FROM ut_elements elements INNER JOIN ut_categories categories ON categories.id = elements.id INNER JOIN ut_elements_sites elements_sites ON elements_sites.elementId = elements.id INNER JOIN ut_content content ON content.elementId = elements.id INNER JOIN ut_structureelements structureelements ON (structureelements.elementId = elements.id) AND (structureelements.structureId=:qp0) WHERE (categories.groupId=:qp1) AND (elements_sites.siteId=:qp2) AND (title = :qp3) AND (content.siteId=:qp4) AND (elements.archived=:qp5) AND (elements.dateDeleted IS NULL) AND (elements_sites.enabled=:qp6) ORDER BY structureelements.lft, elements.dateCreated DESC) subquery INNER JOIN ut_categories categories ON categories.id = subquery.elementsId INNER JOIN ut_elements elements ON elements.id = subquery.elementsId INNER JOIN ut_elements_sites elements_sites ON elements_sites.id = subquery.elementsSitesId INNER JOIN ut_content content ON content.id = subquery.contentId INNER JOIN ut_structureelements structureelements ON (structureelements.elementId = subquery.elementsId) AND (structureelements.structureId=:qp7) ORDER BY structureelements.lft, elements.dateCreated DESC - Command.php: 264.

### Steps to reproduce

1. Create categories and assign to entry type
2. Setup FeedMe  
  
![bildschirmfoto 2019-02-02 um 18 36 25](https://user-images.githubusercontent.com/10465787/52167856-89bc5e80-2719-11e9-94ff-cffd347fedc8.png)

3. Import JSON with categories like shown below  
```json
[
  {
    "id": "479310",
    "title": "foo",
    "services": ["Cleaning", "Dog walking"]
  }
]
```

### Additional info

- Plugin version: 3.1.2
- Craft version: 3.1.7

**Comment by danireginatto** [comment]
+1

**Comment by urbantrout** [comment]
@danireginatto In which version exactly did it work?

**Comment by engram-design** [comment]
Thanks for letting me know - investigating...

**Comment by engram-design** [comment]
Still trying to replicate this without much luck. Are people using MySQL or Postgres?

Have you tried running the debug action to see if the issue still occurs when doing that?

**Comment by urbantrout** [comment]
Updating feed-me to version 3.1.3 solved the problem for me.

**Comment by urbantrout** [comment]
@engram-design thanks for your help!

**Comment by engram-design** [comment]
Great! Was also going to suggest trying in [3.1.5](https://github.com/verbb/feed-me/releases/tag/3.1.5), but 3.1.3 did fix a pretty major issue caused by a PR I didn't check thoroughly in 3.1.2...

**Comment by danireginatto** [comment]
This problem has not been resolved.
For my import it continues to duplicate the categories.



Daniel Reginatto
daniel@reginatto.com

**Comment by urbantrout** [comment]
@danireginatto I guess that is a different issue. I never had duplicates…

**Comment by engram-design** [comment]
@danireginatto Are you still receiving this error along with duplicate categories? If not, best to open a new issue with some information on your setup and what's going on. Or, better yet, send through a Help request through the plugin, and I can take a look.
