### ISSUE TITLE
Asset generation fails after update from 3.1.0 to 3.1.2

### ISSUE THREAD

**Issue by hashchange** [verbb/feed-me#465]
One of my feeds is supposed to generate assets from an attribute in the RSS, but that has stopped working after updating from 3.1.0 to 3.1.2. A rollback to 3.1.0 has fixed it. The feed settings have stayed the same all along.

I've seen it happen in 

- Windows/XAMPP, PHP 7.1.16, Craft 3.1.8
- Ubuntu 18.04, PHP 7.2.14, Craft 3.1.8

I didn't test if the problem has been asset generation in general, or the fact that the URL is located in an XML attribute:
    
    <item>
        <enclosure url="https://..."/>
    </item>
    
In my settings, I've checked the "Create asseet from URL" box, keeping existing assets. You can have a look at the feed data [here](https://feeds.t-online.de/rss/tagesanbruch).

Any thoughts?

**Comment by engram-design** [comment]
Actually not able to reproduce this, and seems to be working well in the latest version.

Would you be able to give [3.1.5](https://github.com/verbb/feed-me/releases/tag/3.1.5) a go?

**Comment by hashchange** [comment]
I've tried my luck with 3.1.6 today and the issue is gone. Thanks!
