### ISSUE TITLE
The Default Value field mapping of a Lightswitch is never checked

### ISSUE THREAD

**Issue by johndwells** [verbb/feed-me#467]
### Description

While editing the field map, if a field is a Lightswitch and one chooses "on" as the Default value, after saving and returning to the mapping page, the Lightswitch is not toggled on.

Caused by 152 in `_includes/fields/base.html`:

```
checked: defaultValue,
```

Should instead be:

```
on: defaultValue,
```

### Steps to reproduce

1. Go to edit a feed mapping
2. Set a Lightswitch's  default value to on
3. Save feed mapping
4. Return to feed mapping
5. Lightswitch default value is still off

### Additional info

- Plugin version: 3.0.2.1
- Craft version: 3.0.40

**Comment by engram-design** [comment]
Whoops, right you are! Fixed in [3.1.5](https://github.com/verbb/feed-me/releases/tag/3.1.5)
