### ISSUE TITLE
Unable to register extension "verbb\feedme\web\twig\Extension" as extensions have already been initialized.

### ISSUE THREAD

**Issue by johndwells** [verbb/feed-me#468]
### Description

I am periodically seeing a LogicException thrown by Feed Me:

```
Unable to register extension "verbb\feedme\web\twig\Extension" as extensions have already been initialized.
```

It will appear and then if I reload the page, will disappear. I have found that if I trash `storage/runtime/compiled_templates/` that the error will come back.

In my tests I have found that if I wrap the line that registers the extension in a check to ensure it's a web request (as per Craft's docs: https://docs.craftcms.com/v3/extend/extending-twig.html#extend-the-global-craft-variable), that this prevents the error from being thrown. e.g.:

```
if (Craft::$app->request->getIsSiteRequest()) {
    Craft::$app->view->registerTwigExtension(new Extension());
}
```

### Additional info

- Plugin version: 3.0.2.1
- Craft version: 3.0.40

**Comment by johndwells** [comment]
That fix is actually not right... only registering it on the site request means that the extension isn't available in the CP, which is where it's needed.  Yet when I change it to `getIsCpRequest()` then it's still being thrown...

So I don't know what is happening. I don't know if it's just this install, if there is a conflict with another plugin or our custom module...

:(

**Comment by johndwells** [comment]
I don't think this is a Feed Me bug... I've disabled the SearchIt plugin and that makes the error go away. I've tracked it down to SearchIt calling `Craft::$app->getView()` within it's own `init()` routine and I think that's the issue.

I'm going to report it over there...

https://github.com/fruitstudios/craft-searchit/issues/10

**Comment by engram-design** [comment]
Ah yes, I think I've seen that issue before with another plugin. To be honest, I'm actually following what Commerce does, which isn't anything special - https://github.com/craftcms/commerce/blob/develop/src/Plugin.php#L229
