### ISSUE TITLE
Default entry status ignored

### ISSUE THREAD

**Issue by janhenckens** [verbb/feed-me#469]
### Description
I have a feed where I want to import everything as disabled so the client can enable the entries that should be disabled.

Tried to solve it like this: don't import a status, don't set a default value and have the default status vor the section be disabled. But the entries are imported as enabled anyway.

Is this the wrong way to go about this?
Thanks!

(see also #270 and #234)

### Steps to reproduce

* Set the Default Entry Status of a section to `disabled`.
* Setup an import for the section. On the fields option screen, set the Status option to `Don't Import`.
* Import data into the section.

### Additional info

- Plugin version: 3.14
- Craft version: 3.1.8

**Comment by engram-design** [comment]
Should be fixed in [3.1.5](https://github.com/verbb/feed-me/releases/tag/3.1.5)

**Comment by janhenckens** [comment]
Thanks!

**Comment by icreatestuff** [comment]
I'm seeing this same issue in 4.1.0

**Comment by brandonkelly** [comment]
@icreatestuff You are seeing it when creating **new** entries?

**Comment by icreatestuff** [comment]
Hi @brandonkelly yes that's right, when creating new entries.
