### ISSUE TITLE
Misnamed variable $uploadedElementIds in User.php

### ISSUE THREAD

**Issue by john-henry** [verbb/feed-me#471]
### Description

User.php https://github.com/verbb/feed-me/blob/craft-3/src/elements/User.php#L236

`$uploadedElements = AssetHelper::fetchRemoteImage([$urlToUpload], $fieldInfo, $this->feed, null, $this->element, $folderId);`

needs to be 

`$uploadedElementIds = AssetHelper::fetchRemoteImage([$urlToUpload], $fieldInfo, $this->feed, null, $this->element, $folderId);`

### Steps to reproduce

1. Update users with profile photo
2. Variable not found error

### Additional info

- Plugin version: 3.1.4
- Craft version: 3.1.8

**Comment by engram-design** [comment]
Whoops, thanks! Fixed in [3.1.5](https://github.com/verbb/feed-me/releases/tag/3.1.5)
