### ISSUE TITLE
Importing related products to a product variant - only first product is related

### ISSUE THREAD

**Issue by fantasticmachine** [verbb/feed-me#473]
### Description
I have Commerce Variants that contain a field relating other Commerce Products.
There could be multiple products related via this field.
Import runs OK but only the first related product gets imported to the field.

A sample XML file is attached. The field in question is named "Grout" with each related item being within the <cat> node.
For instance

`<grout><cat>Medium Grey</cat><cat>Silver Grey</cat><cat>White</cat></grout>`

In the above instance, only the "Medium Grey" grout product gets related.

All the grout entries already exist.

[handmadewalltiles copy.xml.zip](https://github.com/verbb/feed-me/files/2851979/handmadewalltiles.copy.xml.zip)

### Steps to reproduce

1. Create some Commerce Products with multiple variants of each.
2. Create a product relationship field in order to relate Commerce Products to the variants from step 1.
3. Run an XML import, assigning the Grout element to the relationship field.

### Additional info

- Plugin version: Feed Me 3.1.5, Feed Me Pro 3.0.4
- Craft version: 3.1.8

**Comment by engram-design** [comment]
Not able to replicate this I'm afraid, and I'm using a cut-down version of your feed:

```
<?xml version="1.0" encoding="utf-8" ?>
<tilestest>
    <custom>
        <row>
            <title>One</title>
            <sku>One-11</sku>

            <products>
                <product>Sample Product 1</product>
                <product>Sample Product 2</product>
            </products>
        </row>

        <row>
            <title>Two</title>
            <sku>One-22</sku>

            <products>
                <product>Sample Product 1</product>
                <product>Sample Product 2</product>
            </products>
        </row>
    </custom>
</tilestest>
```

In my case, it's including the two products in my products field. 

Its worth asking, but are you setting any limits on your products field?

**Comment by fantasticmachine** [comment]
Hi Josh,

No there’s no limit on the related field.

The field in question is within a Variant rather than a Product.

I have 2 product types - “Tiles” and “Accessories”
“Tiles” products have multiple variants. The field in question is within the variant and is a Commerce Products field to make a relationship between the Tile variant being updated and 1 or more of the products in the Accessories type.

For example (removed a lot of fields here for clarity)

<?xml version=“1.0” encoding=“utf-8” ?>
<tiles>
	<custom>
		<variant>
			<id>125</id>
			<productname>Savernake</productname>
			<variantname>Angel Yard Square</variantname>
			<productcode>SAVANG13X13</productcode>
			<grout> #each of these should create a relationship to an Accessory product but only the first one is being related#
				<product>Limestone</product>
				<product>Medium Grey</product>
				<product>Silver Grey</product>
				<product>White</product>
			</grout>
			<suitability>
				<cat>wall</cat>
				<cat>kitchen</cat>
				<cat>bathroom</cat>
				<cat>shower-walls</cat>
				<cat>hearth-fireplace-surrounds</cat>
				<cat>cooker-splashbacks</cat>
				<cat>commercial</cat>
			</suitability>
		</variant>

	</custom>
</tiles>

In the above example, Grout is mapped to a Commerce Products field (with no restrictions on it) and should create a relationship between the Commerce Variant being created/updated and the Commerce Products in the <grout/product> nodes. But it only creates the relationship to the first node (in this case “Limestone”). This has worked fine in the past but the last import I ran behaved differently.

In contrast, the Suitability items are relating to Craft Categories and these all get related.

If I look in FeedMe’s logs at the first variant being updated I can see that it’s only got a single value in the array for the grout field

"complimentaryGrout":["1036”]

I’ll keep digging to see if I can figure out what’s going on.

Cheers
Pete (Foamcow in Slack/Discord)

**Comment by fantasticmachine** [comment]
Hi Josh,

No there’s no limit on the related field.

The field in question is within a Variant rather than a Product.

I have 2 product types - “Tiles” and “Accessories”
“Tiles” products have multiple variants. The field in question is within the variant and is a Commerce Products field to make a relationship between the Tile variant being updated and 1 or more of the products in the Accessories type.

For example (removed a lot of fields here for clarity)
```
<?xml version=“1.0” encoding=“utf-8” ?>
<tiles>
	<custom>
		<variant>
			<id>125</id>
			<productname>Savernake</productname>
			<variantname>Angel Yard Square</variantname>
			<productcode>SAVANG13X13</productcode>
			<grout> #each of these should create a relationship to an Accessory product but only the first one is being related#
				<product>Limestone</product>
				<product>Medium Grey</product>
				<product>Silver Grey</product>
				<product>White</product>
			</grout>
			<suitability>
				<cat>wall</cat>
				<cat>kitchen</cat>
				<cat>bathroom</cat>
				<cat>shower-walls</cat>
				<cat>hearth-fireplace-surrounds</cat>
				<cat>cooker-splashbacks</cat>
				<cat>commercial</cat>
			</suitability>
		</variant>

	</custom>
</tiles>
```
In the above example, Grout is mapped to a Commerce Products field (with no restrictions on it) and should create a relationship between the Commerce Variant being created/updated and the Commerce Products in the <grout/product> nodes. But it only creates the relationship to the first node (in this case “Limestone”). This has worked fine in the past but the last import I ran behaved differently.

In contrast, the Suitability items are relating to Craft Categories and these all get related.

If I look in FeedMe’s logs at the first variant being updated I can see that it’s only got a single value in the array for the grout field

"complimentaryGrout":["1036”]

I’ll keep digging to see if I can figure out what’s going on.

**Comment by fantasticmachine** [comment]
This now seems to be happening with any type of relationship within a variant.

**Comment by fantasticmachine** [comment]
This certainly seems to be an issue when the field in question is at the Variant level.
I put the same field in both the Product element and the Variant element. The Product element gets updated with all related Products but the Variant only gets updated with the first one.

**Comment by engram-design** [comment]
Ah - you are completely right here, and that's my fault. I was sure I setup a test with the product on the variant, but looking back at this, and I only tested with the field on the product. Your issue is indeed correct - sorry about that!

This also comes down to the structure of your feed, which Feed Me is a bit opinionated about (see https://verbb.io/craft-plugins/feed-me/docs/guides/importing-commerce-variants). The feed structure typically follows a surrounding product, then multiple variants within that. In your instance, you're skipping ahead to variants - which is fine in theory. There's just a bunch of use-cases where feeds differ, so we need to cater for all sorts of structures.

Should be sorted in [3.1.7](https://github.com/verbb/feed-me/releases/tag/3.1.7)

**Comment by fantasticmachine** [comment]
Ah that explains why it once worked as I was structuring the feed in that way. The client is sending me the data in a spreadsheet where each row is a variant. I’m then importing into a MySQL table and exporting as XML. Because of the way they send the data to me it’s easier to structure it as I now have rather than figure out a query to group it into products.

So when you say “Should be sorted in 3.1.7” does that mean it’ll be able to cater for my feed structure or shall I go ahead and make some new XML with a product->variant structure?

**Comment by engram-design** [comment]
You feed should work as-is in 3.1.7
