### ISSUE TITLE
Mapping to parent via custom field does not work

### ISSUE THREAD

**Issue by Kota-M** [verbb/feed-me#474]
### Description
I would like to import some entries from CSV, and set their parents via custom field.
However, it is failed.
I found that parent mapping works if I use entry ID.

Could you help me to import correctly?

### Steps to reproduce

1. Create a custom field called "Old ID" for parent entries, and set values for each ones
2. Create a new feed and select "Old ID" for Parents, and set it also for "Data provided for this entry is"
3. Save the feed, and run it
4. Some entries are created, but their parents are not set

The CSV is like this:
"Name","Description","Keywords","Old ID"
"Alpha","1st","A","778"
"Beta","2nd","B","782"
"Gamma","3rd","C","790"

### Additional info

- Plugin version: 3.0.2.1
- Craft version: 3.0.34

**Comment by engram-design** [comment]
Fixed in [3.1.6](https://github.com/verbb/feed-me/releases/tag/3.1.6).
