### ISSUE TITLE
Email not a valid address - if whitespace

### ISSUE THREAD

**Issue by Coysh** [verbb/feed-me#475]
### Description
if an email address is uploaded with whitespace at the end (i.e. `bob@bob.com `) - the node upload will fail with:
`Node #XX - {"email":["Email is not a valid email address."]} - Process.php: 454`

### Steps to reproduce
1. Create CSV to upload to user, with whitespace at the end of email address
2. Process feed

### Additional info

- Plugin version: 3.1.4
- Craft version: 3.1.8

**Comment by engram-design** [comment]
Fixed in [3.1.6](https://github.com/verbb/feed-me/releases/tag/3.1.6).
