### ISSUE TITLE
Single Folder Asset PostgreSQL Error + Unexpected Behavior

### ISSUE THREAD

**Issue by leigeber** [verbb/feed-me#476]
### Description

When the "Restrict uploads to a single folder?" option is selected on a mapped field Feed Me is resolving the sources as "*" per the fields "sources" setting in the database but that is translating into an invalid LIKE '%' query in PostgreSQL. Besides that issue by itself I would assume the intended behavior should be to use the "singleUploadLocationSource" value on the file settings if "useSingleFolder" is 1.

Undefined function: 7 ERROR: operator does not exist: bigint ~~ unknown LINE 7: WHERE ("assets"."folderId" LIKE $1) AND ("assets"."filename"... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. The SQL being executed was: SELECT "elements"."id" FROM (SELECT "elements"."id" AS "elementsId", "elements_sites"."id" AS "elementsSitesId", "content"."id" AS "contentId" FROM "craft_elements" "elements" INNER JOIN "craft_assets" "assets" ON "assets"."id" = "elements"."id" INNER JOIN "craft_elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id" INNER JOIN "craft_content" "content" ON "content"."elementId" = "elements"."id" WHERE ("assets"."folderId" LIKE '%') AND ("assets"."filename"='http://s3-us-west-2.amazonaws.com/xxx.jpg') AND ("assets"."kind"='image') AND ("elements_sites"."siteId"=1) AND ("content"."siteId"=1) AND ("elements"."archived"=FALSE) AND ("elements"."dateDeleted" IS NULL) AND ("elements_sites"."enabled"=TRUE) ORDER BY "elements"."dateCreated" DESC LIMIT 1) "subquery" INNER JOIN "craft_assets" "assets" ON "assets"."id" = "subquery"."elementsId" INNER JOIN "craft_volumefolders" "volumeFolders" ON "assets"."folderId" = "volumeFolders"."id" INNER JOIN "craft_elements" "elements" ON "elements"."id" = "subquery"."elementsId" INNER JOIN "craft_elements_sites" "elements_sites" ON "elements_sites"."id" = "subquery"."elementsSitesId" INNER JOIN "craft_content" "content" ON "content"."id" = "subquery"."contentId" ORDER BY "elements"."dateCreated" DESC

### Additional info

- Plugin version: 3.1.5
- Craft version: 3.1.9.1

**Comment by engram-design** [comment]
Fixed in [3.1.6](https://github.com/verbb/feed-me/releases/tag/3.1.6).
