### ISSUE TITLE
Removing table rows

### ISSUE THREAD

**Issue by stromjoe** [verbb/feed-me#477]
**### Description**
Unable to remove table rows.

**### Steps to reproduce**
With a table structure like below, removing everything inside [] does not seem to be reflected in the updated entry after running the feed, the row with all of it's data still shows.

    "PRESENTATIONS": [
      {
        "PRESENTATION_ID": 1792050,
        "AGENT_NAME": "Agent Name",
        "PRESENTATION_INFO": null,
        "PRESENTATION_START": "2020-02-18 17:05:00+02:00",
        "PRESENTATION_END": "2019-02-18 17:10:00+02:00"
      }
    ]

Running the updated feed with only an empty [] still includes all of the data from the previous version.
Removing or changing individual column data works as expected (ex. changing AGENT_NAME value works after running the feed again).

**### Additional info**
How is one supposed to completely delete whole rows or all of a table's data?

- Plugin version: 3.0.2.1
- Craft version: Craft Pro 3.0.32

**Comment by engram-design** [comment]
Fixed in [3.1.7](https://github.com/verbb/feed-me/releases/tag/3.1.7)
