### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by engram-design** [verbb/feed-me#479]
Getting error:

Message: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by engram-design** [comment]
Setting this in your `feed-me.php` config file should fix the issue:

```
<?php

return [
    '*' => [
        'clientOptions' => [
            'verify' => false,
        ],
    ],
];
```

**Comment by jamesmacwhite** [comment]
It's worth mentioning that this error could be hinting at a potentially bigger problem with the PHP cURL/OpenSSL setup related to cURL CA verification. Disabling this isn't ideal if it's masking this problem. It usually means PHP has not been configured properly and you'd need to change a few options.

Example: https://github.com/FilipQL/cacert.pem
https://curl.haxx.se/docs/caextract.html

This requires full access to the environment however.
