### ISSUE TITLE
SQL Integrity constraint violation

### ISSUE THREAD

**Issue by goellner** [verbb/feed-me#480]
### Description

Getting error message with feed-me pro. 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7312613225' for key 'sln_commerce_variants_sku_unq_idx'

### Steps to reproduce

1. Import commerce products from JSON feed
2. Delete all products from admin panel
3. Import commerce products again
4. Import skips all items, because of existing SKU

### Additional info

- Plugin version: 3.1.8 (free) / 3.0.4 (pro)
- Craft version: Craft Pro 3.1.9.1

**Comment by engram-design** [comment]
I've noticed this as well, and believe its a bug in Commerce - https://github.com/craftcms/commerce/issues/718

**Comment by buesing** [comment]
I think it's also related to this: https://github.com/craftcms/commerce/issues/734
Manually deleting the items, then running `./craft gc/run`, then re-importing doesn't throw the error. Is there any way to automatically run the garbage collection after items are deleted by feed me? This prevents us from doing automated imports which is necessary for our client. cc @supportverbb

**Comment by engram-design** [comment]
@buesing We'll look into this for sure. However, its arguably different behaviour from any other Craft element (this doesn't occur for Entries, Categories, etc), so I do feel like this is still a Commerce bug cc @lukeholder.

**Comment by engram-design** [comment]
In the meantime, I've added a config option `runGcBeforeFeed`, which is off by default, but that might help.

**Comment by lukeholder** [comment]
Will be fixed in the next Commerce release.

**Comment by lukeholder** [comment]
Fixed in craftcms/commerce#715

**Comment by engram-design** [comment]
Thanks @lukeholder!
