### ISSUE TITLE
FR: Custom data feeds and additional boolean values

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/feed-me#481]
### Description

Could the boolean values currently being provided by the parseBoolean function in `/src/helpers/BaseHelper.php` be developed further to allow custom feed types to provide additional boolean values, without modifying the core of the plugin?

For a certain type of feed data we have very bespoke values that determines if an entry is enabled/disabled. Some of which don't make sense generally, so committing them directly to the source wouldn't seem logical for general use cases and start to pollute the core plugin.

As an example, we have a data feed with a status field linked with the Craft entry status but it can have exotic values, such as "INCOMPLETE". For the purpose of this data feed it actually makes the entry enabled, but from a enabled/disabled scenario doesn't make any sense as a boolean, but hey that's custom business logic!

It would be nice if custom feeds could extend the boolean values for this purpose. Or if there would be another way to add additional boolean values without hacking the core plugin.

Hope that makes sense!

**Comment by engram-design** [comment]
There's no hooks for booleans, but you can use an event field [field parsing](https://verbb.io/craft-plugins/feed-me/docs/developers/field-types) to hook into the parsed values for your fields.

```
Event::on(Fields::class, Fields::EVENT_AFTER_PARSE_FIELD, function(FieldEvent $e) {
    $fieldHandle = $e->fieldHandle;
    $parsedValue = $e->parsedValue;
    
    if ($fieldHandle == 'myCustomField') {
        // Parse boolean
    }
});
```

Would that work?

**Comment by jamesmacwhite** [comment]
Thanks for this. I haven't gotten around to testing FeedMe 3 yet for this feed, but it looks potentially promising.

In this scenario then, let's say fieldHandle `==` 'INCOMPLETE`. Within the conditional, what would you do to essentially force the entry status to be enabled, given this value would not be picked up by the base parse boolean list. Would you target the entries enabled field itself and set it to true?

```$e->enabled = true```?

**Comment by engram-design** [comment]
Close! `$e->element->enabled = false;` will do the trick.

**Comment by jamesmacwhite** [comment]
Thanks Josh. Will look at testing this out during our Craft 3 migration!
