### ISSUE TITLE
Duplicate craft tasks in big import

### ISSUE THREAD

**Issue by pieter-janDB** [verbb/feed-me#483]
### Description

I am merging 15 craft 2 sites under 1 craft cms 3 site.. I made endpoints that deliver the json that is being imported by feedme. Everything works fine here (only supertables inside of matrix did not work so I had to write a manual import for those).

Now after starting the import for the first site, everything is imported as expected (lets say around 1000 entries) But after it is finished craft has a really full queue ( craft 2 tasks ) of about 900 tasks, They look like they are all duplicates of eachother (like generating products sitemap x 300 for every product) Is there any way to prevent these tasks from being triggered that many times? 

All these tasks take longer then the actual import..

### Steps to reproduce

1. Craft 3 import of big amount of entries
2. check tasks

### Additional info

- Plugin version: Feed Me 3.1.10 / Pro 3.0.4
- Craft version: Craft CMS 3.1.15

**Comment by engram-design** [comment]
To clarify, are the Feed Me tasks duplicating? The are the `Running x feed` items in your queue.

The `Generating x sitemap` are triggered by SEOmatic I believe, but the latest versions of each plugins should be looking for a special value that Feed Me sets so that it doesn't fire off these rapid event changes. You also mention products, are you importing entries or products (or both)?

**Comment by pieter-janDB** [comment]
Hi, thanks for the feedback.

To clarify: The feedme tasks don't get duplicated they run as intended. But after they have ran I have a whole lot of tasks that get triggered when saving entries like the `Generating x sitemap` you mentioned from SEOmatic.
I am only importing entries (there are just some entries that represent products but there is no craft commerce in the site)

I also change some seomatic values with a custom import script so I am just gonna disable this and the seomatic plugin before running the feedme feeds, I might do some more tests later but I have to complete the import asap and this method seems to work fine..

**Comment by pieter-janDB** [comment]
This issue can be closed, I found what was triggering this and it wasn't a bug in Feed me.
