### ISSUE TITLE
Create asset folders from path

### ISSUE THREAD

**Issue by Tam** [verbb/feed-me#485]
### Description
I'm trying to import assets from an old Craft 2 site to a new Craft 3 site. I'm passing the folder path with each asset as `Parent-Folder/Sub-Folder/`, but the assets are all imported at the volume root.

Do the folders need to exist before hand, or will it only work with a single folder name? I assume Feed Me doesn't create the folders automatically?

### Steps to reproduce

1. Import assets, passing a folder path to the folder field.

### Additional info

- Plugin version: 3.0.4
- Craft version: 3.1.16

**Comment by engram-design** [comment]
So just to clarify, is your feed importing assets (only), or are they importing entries and assets, using an asset field?

If the latter, you can specify the folder through the `Location` options for the field. Feed Me will look at this value, and if you're suppling a value in there (static or dynamic), it'll sort out where to put the asset.

If you're importing assets, using Feed Me Pro - you can set the folder in the field mapping step, by either selecting a node in your feed that contains the folder name (just the folder name), or select a default folder from the list provided.

But - to answer your question, it looks like we don't create the folders if they don't exist. I've added this as an option in [3.1.15](https://github.com/verbb/feed-me/releases/tag/3.1.15)

The reason that we don't assume the path in your feed should equate to how its structured in Craft is that there's such a wide variety of formats to cater for. If you're trying to upload assets from a remote URL, should we create folders based on the URL path? Similarly for local assets as well.
