### ISSUE TITLE
Unable to access license key field in new Pro edition

### ISSUE THREAD

**Issue by tinchalamo** [verbb/feed-me#486]
### Description
Updated to 3.1.14, but not seeing a license key field to enter in my Feed Me Pro license to the new Pro edition of Feed Me.

### Steps to reproduce

1. Update plugin to 3.1.14
2. No visible license key field in Settings → Plugins page in Control Panel: ![image](https://user-images.githubusercontent.com/11000310/54057376-6a9d6a80-41b8-11e9-9f34-a6a1d8f4b442.png)

### Additional info

- Plugin version: 3.1.14
- Craft version: 3.1.17

**Comment by engram-design** [comment]
I believe this _may_ be a Craft bug, but will update you shortly.

**Comment by engram-design** [comment]
This should be fixed in [3.1.17.1](https://github.com/craftcms/cms/releases/tag/3.1.17.1)

**Comment by tinchalamo** [comment]
Strangely, after updating Craft I see it on my local environment, but on my production environment I don't see the license key field and it has the label of LITE.

**Comment by tinchalamo** [comment]
@engram-design any advice? I'm trying to use the Feed Me plugin on production, but since it's the lite version I don't have all the features available. I have a license, but there's no place to input it from what I can tell. Please advise.

**Comment by engram-design** [comment]
@tinchalamo The license key is stored in the database, so you'll need to manually update the plugin from Lite to Pro on each environment you have. You'll need to click on the Lite badge to be taken to the plugin store, where you can upgrade to the Pro edition.

An alternative would be to have project config enabled on your project, which would store plugin settings in a project.yaml file.

**Comment by tinchalamo** [comment]
@engram-design ah, totally missed clicking on the Lite label. Thanks Josh!
