### ISSUE TITLE
Multi-language entry won't update

### ISSUE THREAD

**Issue by loqus** [verbb/feed-me#487]
### Description

I have a site with 4 languages. I've used Feed me to import the first language and update the field contents with other language feeds. But now this doesn't work anymore. For example I import French entries and it all goes well. If I check the entry itself the only active language is FR, the other languages are not found upon selection. This remains when for example I update the entry with the EN version of the entry fields. 

So in the entry list the entries are not visible in the language that hasn't been imported first.

### Steps to reproduce

1. Import 1 language
2. Import second language.

### Additional info

- Plugin version: 3.1.12 (also tried 3.1.15)
- Craft version: Craft Pro 3.1.17.1

**Comment by engram-design** [comment]
What are your section settings? Do you have "Propagate entries across all enabled sites?" set?

I would imagine you're also selecting just the French site on the first setup step for your feed?

**Comment by loqus** [comment]
Propagate entries across all enabled sites is enabled for the section. Per language is 1 import file and feed. I select the section/entry type and 1 site. So for the English xml I use the site: Web EN, and for the french for example: Web FR

**Comment by engram-design** [comment]
I think this might be related to something fixed in [3.1.16](https://github.com/verbb/feed-me/releases/tag/3.1.16). If you have a moment, would be great to test this.

**Comment by mustasj** [comment]
Did you solve this? is it in an unreleased version?

I got this result too, same steps. But i got 3.1.16 and Craft 3.1.21.
The entries for the second language didn't match the slug so it made new entries.
When i deleted all the imports for the second language i cant save the entries for the first language.
I get `Attempting to save an element in an unsupported site.`
