### ISSUE TITLE
Sort Feeds by Name Alphabetically

### ISSUE THREAD

**Issue by benjaminkohl** [verbb/feed-me#488]
### Description

This is a feature request to have the list of feeds sort alphabetically in the control panel. Right now it appears they are listed in the order they were created but this makes it a little more difficult to find the feed I'm looking for when there are 25+ feeds.

**Comment by engram-design** [comment]
I'd rather make this opt-in so as its not a breaking change. Hopefully It'll be something similar to how you can sort elements in a table layout. Personally, I prefer to have them ordered in the order they're created.

Otherwise, worse-case, you'll be able to manually re-order them.

**Comment by benjaminkohl** [comment]
But what is the significance of the order in which they are created? If it's something like they need to be run in that order, then maybe a drag-and-drop sorting of feeds might make the most sense because not everyone is going to construct feeds in the order they need to be run.

In our case, the order they are run doesn't matter so sorting alphabetically just makes the feeds easier for other content admin to locate in the long list that keeps getting longer.

**Comment by ryanmasuga** [comment]
The order feeds are created is almost completely irrelevant on any site on which we've ever used FeedMe. Sometimes we go from easiest feed to hardest to execute - but then the hardest one might ultimately be the most important and most often run feed, but we added it last, so it would be at the bottom of the list for no reason.

**Comment by engram-design** [comment]
Its actually just a carry-over from when Feed Me for Craft 2 actually showed the ID column first, but was removed as its a little useless. As such, they are technically ordered by ID @benjaminkohl, which are sequential from the time they're created.

I'll be implementing manual re-ordering in the next release.

**Comment by engram-design** [comment]
Added manual sorting in [3.1.17](https://github.com/verbb/feed-me/releases/tag/3.1.17).
