### ISSUE TITLE
Queue timing out (

### ISSUE THREAD

**Issue by Coysh** [verbb/feed-me#491]
### Description
In my `craft_queue` my feeds are failing to run via cron:
`The process "/usr/bin/php7.2 craft queue/exec "51992" "300" "1" "" --color=" exceeded the timeout of 300 seconds.`

Seems like the same problem as:
[https://craftcms.stackexchange.com/questions/25437/queue-exec-time](https://craftcms.stackexchange.com/questions/25437/queue-exec-time)

### Steps to reproduce

1. Set up a feed
2. Set it to run via cron

### Additional info

- Plugin version: 3.1.15
- Craft version: Craft Pro 3.1.17.2

**Comment by engram-design** [comment]
I've added `queueMaxRetry` and `queueTtr` config settings for you to tweak to help timeouts of queue jobs in [3.1.16](https://github.com/verbb/feed-me/releases/tag/3.1.16)
