### ISSUE TITLE
defaultVariantId not set on first import

### ISSUE THREAD

**Issue by goellner** [verbb/feed-me#493]
### Description
When importing products to Craft Commerce, the `defaultVariantId` doesn't get set on the first run of the import. When the import is run again, the `defaultVariantId` gets set in the database.

The `defaultVariantId` should be set in the first import.

### Steps to reproduce

1. Import JSON feed to commerce products
2. Look at `defaultVariantId` in database -> empty
3. Run feed again
4. `defaultVariantId` is set

### Additional info

- Plugin version: 3.1.15
- Craft version: Craft Pro 3.1.18

**Comment by engram-design** [comment]
Yup, so looks like Commerce doesn't save the product's variants first, then set the defaultVariantId. That's the reason its only doing it after the first save. To confirm, create a product with multiple variants manually, and you'll get the same behaviour.

Might reference this on Commerce...

**Comment by engram-design** [comment]
Closing for now...

**Comment by lukeholder** [comment]
Fixed for the next release of commerce.

**Comment by engram-design** [comment]
Champion, thanks @lukeholder
