### ISSUE TITLE
Allow third party fields (that extend base types) as unique identifiers

### ISSUE THREAD

**Issue by EternalBlack** [verbb/feed-me#495]
### Description

I'd like to use [IncognitoField](https://github.com/mmikkel/IncognitoField-Craft3) as unique identifier as it solves the problem that the entries (after import) can and should be altered by an editor but certain content should remain locked as it's the unique identifier.

### Steps to reproduce

1. Make a field an `Incognito Field`
2. Create a feed
3. Try to select the `Incognito Field` as Unique Identifier
4. Realize it's not there
5 Cry

### Additional info

- Plugin version: 3.1.16 Pro
- Craft version: 3.1.19 Pro

**Comment by engram-design** [comment]
Added in [3.1.17](https://github.com/verbb/feed-me/releases/tag/3.1.17).
