### ISSUE TITLE
SimpleMap: error attempting to populate empty addresses when lat/lng also empty

### ISSUE THREAD

**Issue by BridgingUnit** [verbb/feed-me#502]
Another catch in https://github.com/verbb/feed-me/blob/craft-3/src/fields/SimpleMap.php

Line 54 should probably read:

`        if ( (isset($preppedData['lat']) && !empty($preppedData['lat'])) && (isset($preppedData['lng']) && !empty($preppedData['lng'])) ) {`

Instead of:

 `        if (isset($preppedData['lat']) || isset($preppedData['lng'])) {`

because we need _both_ lat/lng to use the _getAddressFromLatLng function, and neither of those should be empty either.

My feed was pulling in lat, long, and zoom, but not address (the EE version being pulled in from doesn't have one to pull in). However, some entries have _no_ lat/long/zoom available at all, but Feed Me was still using the empty values for these, thinking it has something to work with, when in reality it doesn't.

Hope that makes sense.

Latest version of Craft (3.1.19), FeedMe (3.1.16) and Map (3.4.4)

**Comment by engram-design** [comment]
Fixed in [3.1.17](https://github.com/verbb/feed-me/releases/tag/3.1.17).
