### ISSUE TITLE
Installation not working (without any error)

### ISSUE THREAD

**Issue by bertheyman** [verbb/feed-me#507]
### Description
After installation, Feed Me is visible in my plugin section but lists as "not installed".
When clicking "install", ~no error is thrown but nothing changes~ a message is shown "plugin can not be installed". (overlooked it the first time)
I've been able to install other plugins and Craft works without issues.
_Sidenote: I'm new to Craft so if I can provide any extra useful info, feel free to tell me._

### Steps to reproduce

1. Install.
2. Go to plugin section, try to install again.

### Additional info

- Plugin version: 3.1.16
- Craft version: Craft Solo 3.1.20.1

**Comment by engram-design** [comment]
Would you be able to look in your `storage/logs/web.log` file? (search for `error`), so see if there are any clues?

**Comment by bertheyman** [comment]
Hmm, it seems the migrations failed on creating a table that already existed, probably from an earlier install that wasn't committed.
Removed it and installs seamlessly now, so my bad.
Thanks for your help!
