### ISSUE TITLE
Generated slugs don't match those generated by Craft

### ISSUE THREAD

**Issue by smcyr** [verbb/feed-me#508]
### Description

For some titles, the generated slug doesn't match the one generated by Craft for a new entry.

### Steps to reproduce

1. Feed an entry with the title `AG 3500 - ДЛЯ МАШИН С ЖЁСТКОЙ ПЕРЕДАЧЕЙ`
2. Feed me generate this slug: `ag-3500---dl-ya-ma-sh-in-s-zh-estkoy-pereda-ch-ey`
3. Craft 3 generate this slug: `ag-3500-dlya-mashin-s-zhestkoy-peredachey`
4. See the difference

### Additional info

- Plugin version: 3.1.16
- Craft version: 3.1.21.1

**Comment by engram-design** [comment]
Thanks for your PR, accepted and will be in the next release.
